### ISSUE TITLE
urlSync change window.location.pathname

### ISSUE THREAD

**Issue by tecmusti** [algolia/instantsearch.js#1001]
I want change window.location.pathname with category slug. I need this for two reasons
1. New path will be tracked by Google Analytics using ga('set', 'page', '/new-page.html');
2. Sharing a beautiful url is always better than a dirty long url.

Is there a way to define a custom getFullURL function?

**Comment by vvo** [comment]
Hey Hi! I am not sure to completely understand your usecase. Maybe you could have /categories landing pages that would instantiate instantsearch.js instances on their own with some default parameters? That way the pathname would already be the right one.

**Comment by tecmusti** [comment]
I have already done that @vvo. For example at category page (/women-clothes) if I click on a sub category (dresses) in hierarchicalMenu widget I want pathname to be /dresses.

My current configuration: 
```javascript
var locationPath = window.location.pathname;
var searchParameters = {
    hierarchicalFacetsRefinements : {category: ['Women > Clothes']}
}
var defaultParams = {
    appId: 'XXXXXX',
    apiKey: 'XXXXXX',
    indexName: 'XXXXXX',
    searchParameters: searchParameters,
    urlSync:{
        useHash: false,
        trackedParameters:['query','page','facetsRefinements','disjunctiveFacetsRefinements','numericRefinements']
    }
}
var search = instantsearch(defaultParams);
var firstTime = true;
search.on('render', function() {
    $('#categories a').click(function(){
        locationPath =  '/'+$(this).data('slug');
    });
    if(!firstTime){
        ga('set', 'page', locationPath);
        ga('send', 'pageview');
    }
    firstTime = false;
});
```
Then I downloaded instantsearch.js and edited that line;
```javascript
function getFullURL(relative) {
    //return getLocationOrigin() + window.location.pathname + relative;
    return getLocationOrigin() + locationPath + relative;
}
```
So I will need to check new versions of instantsearch.js, download again and update :confounded: 

But such a solution would be great:
```javascript
var defaultParams = {
    appId: 'XXXXXX',
    apiKey: 'XXXXXX',
    indexName: 'XXXXXX',
    locationPath: window.location.pathname,
    searchParameters: searchParameters,
    urlSync:{
        useHash: false,
        trackedParameters:['query','page','facetsRefinements','disjunctiveFacetsRefinements','numericRefinements']
    }
}
var search = instantsearch(defaultParams);
search.on('render', function() {
    $('#categories a').click(function(){
        search.helper.setLocationPath('/'+$(this).data('slug'));
    });
}
```

**Comment by vvo** [comment]
If your website is able to show a webpage when /dresses is loaded (so that link can be copy pasted/refresh) then I am down thinking about providing the feature you are talking about.

Basically it would mean provide an API option in urlSync like `urlSync.computeURL` that would be called:
- before updating the url bar
- for each widget asking to create a URL (so that the generated URLS for hierarchical menu can also be using /dress)

And allow you to change it. We should be careful about the back button => it should still work.

Aside from having "clean" custom urls in your urlbar, can't you configure google analytics to track whatever url you want? Since you can issue google analytics tracking hits programmatically.

**Comment by tecmusti** [comment]
Yes my website shows a webpage for each item in hierarchical menu. I can configure google analytics for all urls but that has some disadvantages.
1. Google likes clean and simple urls
2. Sending google a url like .../...?q=w&p=0&dFR[brand][0]=XX&dFR[brand][1]=YY&.... does not seem a good opinion. This will also increase page views because this will send 5 views for a search like "q=white"

Maybe turbolinks can be a solution for this?

**Comment by tecmusti** [comment]
Do you have any plans for this issue @vvo ?

**Comment by vvo** [comment]
@tecmusti Revisiting this issue I will try to get it right:

- You want to have pages like /dresses, when accessed should display dresses
- You want the links in your hierarchicalRefinementList(s) to go through /dresses/red

To solve this, you would only need to be able to provide a hook (function) here: https://github.com/algolia/instantsearch.js/blob/6291bfc47e9b91a0c8ea947355c9f68851187d20/src/lib/url-sync.js#L79

If this is all you need then why not submit a pull request? As an example, I recently added a way to provide a different History.state at each url render (urlbar/refinementList urls): https://github.com/algolia/instantsearch.js/commit/989856cb12c797c881301963c118e2d2b10aa63b

Otherwise I will try to have a go at it. Please confirm to me that this is the only need that would be required to you.

**Comment by tecmusti** [comment]
@vvo Providing a hook for getFullURL function will solve my issue for now. Sorry but I don't know how to submit a pull request :(

**Comment by vvo** [comment]
This issue is very old, I hope @tecmusti you managed to solve it somehow, if not please open a new one (you will see there's a new issue template for you to easily create an example jsfiddle).

If you can get a precise feature proposal then we should be able to implement it.

**Comment by mojtaba-ramezani** [comment]
confounded
