### ISSUE TITLE
Hits widget: transformData functions should be called even if the templates are not specified

### ISSUE THREAD

**Issue by redox** [algolia/instantsearch.js#1006]
The current behavior is to **not** call the `transformData` function if the associated (same name) `template` is not defined. I think it makes a lot of sense to distinguish those 2 concepts and call the `transformData` whatever the defined templates.

**Comment by vvo** [comment]
I guess your underlying problem was to reformat the whole content.hits (not just hits.map) and have them passed to the regular "item" template (instead of having to use allItems template).

The current template behavior is too complex as an API. Most people just want to reorder/reformat the whole hits or some hits. Header/footer transformData are complexifying the API.

Fixing what you are talking about in 1.x might be a little tricky to get right, in particular in term of documentation since this would be more of a workaround a feature that does not exists than a real feature.
