### ISSUE TITLE
Cannot detect/act on empty refinement list

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instantsearch.js#101]
We might want to disable / remove the whole facets block if there is no refinement available.

I'm not really sure how to do this right now.

**Comment by vvo** [comment]
Thank for the feedback.

The usecase in details:

let's say you have a categories panel like so:
![2015-09-21-134540_288x271_scrot](https://cloud.githubusercontent.com/assets/123822/9991100/4ee10f80-6067-11e5-8e57-a120e8e46703.png)

Then when there are no refinements because of the query, you would want to either:
- hide the panel
- display something like "no categories for current query"

The issue with our current API is that we decided to give the user the ability to provide a template PER refinement instead of being able to give a full template like this:

```mustache
<div>
  <div>categories</div>
  {{#noRefinements}}No refinements dude!{{/noRefinements}}
  {{#refinements}}
    <div>{{title}}</div>
  {{/refinements}}
</div>
```

Possible solutions:
- give a full template, but we again raise the issue of "how do we know where the user clicked?". Two solutions for this:
  - force data-attributes to be set for us to target
  - provide full templates using http://wix.github.io/react-templates/
- provide events like .on('refinements') on refinement list where you can subscribe to them and check data.length === 0

First solution should be the chosen one because the "events" solution is a hack to solve something simple here.

Thoughts @algolia/javascript ?

**Comment by redox** [comment]
I would rather add an optional `label` to the widgets (refinementList, sliders, toggle, etc...) and make it render a `<h3>{{ label }}</h3>` if specified. Hide everything when no values.

**Comment by maxiloc** [comment]
yes I agree with @redox 
We can keep the current template but adding an optional label so that it looks like :

```
<div className={this.props.rootClass}>
	if (label) {
		<div>{label}</div>
	}
	<div>
	{facetValues.map(facetValue => {
	  return (
	    <div className={this.props.itemClass} key={facetValue.name} onClick={this.handleClick.bind(this, facetValue.name)}>
	      <Template data={facetValue} template={template} />
	    </div>
	  );
	})}
	</div>
</div>
```

**Comment by vvo** [comment]
It works for your current usecase bit this would be a hack and ultimately is trying to get the full template inside the API by adding ˋlabel`.

It does not answer @Jerskouille usecase who wants to completely hide the panel when no results.

Not very extensive, what about panel footer, wrapper etc..

Label would be a cool shortcut for our current magento need ok but do not looks like a solution to our templating limitations.

Those api changes will come again and again and are already crippling the api (root class, item class, now label then id and ..). All rooting to a templating limitation

Lets fix that instead?

**Comment by vvo** [comment]
Or we provide `values` event for every refinement widget and you can rely on it to know if you do or do not have values. And do whatever you want then

**Comment by maxiloc** [comment]
Totally get your point. For hiding the panel, I was thinking this can be handled by a facetWrapper widget. Having such widget also allows to implement relatively easily #54.
Maybe we will still need events anyway. 
What do you think ?

**Comment by redox** [comment]
> It does not answer @Jerskouille usecase who wants to completely hide the panel when no results.

Not sure I get your point, since the widget is displaying everything, it's easy to hide it when no facet values are available.

> Not very extensive, what about panel footer, wrapper etc..

But most of the time, we only have a label/title -> I would consider it very differently than footers/wrappers/etc.

**Comment by pixelastic** [comment]
I'm not sure I understand the use case here. We currently do not display the label/title, only the list of refinements. If there are no refinements because of the query (ie. no records have the fields on which the widget is supposed to add a refinement list), then we will display nothing.

What did I get wrong here?

In any case, I would keep the widget the simple task of displaying the list. No label/title, no wrapper, no footer. This can be achieved with the underlying HTML markup, directly by the user. I would provide a way to know the current list of refinements from the outside, though. Maybe through an event and let the user toggle an `hidden` CSS class on the list based on that.

On the other hand, we need to be careful with "we just let the user do this or that". The main goal of this project was that the users did not have to do much. We might need to be more clear on what is included in the core widgets and will not be.

**Comment by maxiloc** [comment]
For me it seems weird to have to do any logic to display/hide/show the label of a facet bloc. I am not sure the facet widget is the place to put this. But for me it should be in the library

**Comment by vvo** [comment]
I have a simple proposal since we are building widgets:

- templates.values
- templates.header
- templates.footer

For every widget.

AND events so that you can also do what you want more precisely.

In the end YES it makes sense to have a widget library that is also dealing with headers, footers templates (or simple string).

I will do a simple POC in a PR for you to see.

looks good?

**Comment by redox** [comment]
Go for it @vvo, simplest way to iterate!
