### ISSUE TITLE
searchBox: update the query state when using searchOnEnterKeyPressOnly

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1015]
When using searchOnEnterKeyPressOnly and willing to bind an external button to trigger a search (like a submit button), this will fail because the search state when clicking on submit will not be the right one.

From http://stackoverflow.com/questions/37101823/how-to-fire-a-search-with-instantsearch-js-when-clicking-on-a-button

This should work.

Also ultimately this will be solved by providing the full form/binding a search button in the searchBox: #1060

**Comment by bobylito** [comment]
I had a look at the jsFiddle and it seems that the query is not updated at all before the search.

The search is done but with an empty query and when the results come back, the field is updated to the correct value (empty) because the input was blurred. The value is not retrieved from the search box because it is updated once when the enter key is pressed.

The property used in this example is `searchOnEnterKeyPressOnly`. It doesn't sound like it was meant to support the case where we use a button to trigger the search. Anyhow, the solution I see here could be to update the query value as we type even though we do not trigger the search right away.

What do you think @vvo ?

**Comment by vvo** [comment]
> update the query value as we type even though we do not trigger the search right away.

Yes this should work. I think it was the case at some point.

**Comment by vvo** [comment]
Closing in favor of searchBox improvements #1060

**Comment by vvo** [comment]
There's still a bug, updating the issue description
