### ISSUE TITLE
Input typed "search" instead of "text"? 

### ISSUE THREAD

**Issue by rayrutjes** [algolia/instantsearch.js#1101]
Would it make sense to use a search input instead of text input for the search box widget?

**Comment by LukyVj** [comment]
When you say "The searchbox widget", you mean the DocSearch input ? 

I don't think it would be necessary, since it's already working fine and without any problems, using all the needed components ( the search icon, the clear icon ). 

Also, it would imply that we would have to work more on the style of the input, to make it looks the same everywhere, and to ditch it's "built-in" components ( search icon, clear icon ) in order to akeep ours.

If we would have to change it, I guess we would proceed like the following : 
- Set the input to `type=search` 
- Remove it's browser styles
- Overwrite the built-in components with our components ( search and clear icon )

And it seems overkill to me. But that's just my point. 

Plus, I took the liberty to screenshot this slide of @Shipow presentation about Searchbox.

![](http://puu.sh/pBCRE/86ec6b9a4f.png) 


What do you guys think about it ?

**Comment by rayrutjes** [comment]
By search box widget I mean the search box widget of the instant search lib.
But yes I suppose if we use search type, it will require additional css work. But at the same time it is pretty convenient to have the reset icon.

**Comment by vvo** [comment]
@rayrutjes We are planning on redoing the searchBox widget, see https://github.com/algolia/instantsearch.js/issues/1060

**Comment by vvo** [comment]
As said by @LukyVj, we won't use the type="search" if that requires a lot of extra work to style it, we will see

**Comment by rayrutjes** [comment]
LGTM!

**Comment by Shipow** [comment]
Ok, i'll schedule up the presentation internally. There are things everyone needs to know.
