### ISSUE TITLE
CurrentRefinedValues widget

### ISSUE THREAD

**Issue by Maaark** [algolia/instantsearch.js#1131]
Another question about the currentRefinementsList, is it possible to edit the item template a bit more? 

We've added a cross icon and we only want to have that cross icon clickable.

**Comment by vvo** [comment]
Hi @Maaark,

That is not currently doable sadly for now. We have proposals to allow deep control over the rendering of every widgets but it's not yet ready.

For now I would keep the whole line clickable. Even on a UX side it's always very tricky to force people to click a very specific area (cross) instead of a much larger one.
