### ISSUE TITLE
priceRanges widget shows ranges with no result

### ISSUE THREAD

**Issue by tecmusti** [algolia/instantsearch.js#1132]
I've noticed that priceRanges widget is listing ranges that have no result. A working example can be found here: https://goo.gl/hpiQLL

And is it possible to display count for items?

**Comment by vvo** [comment]
@tecmusti Hi! Unfortunately that is not yet possible given the feature of the Algolia REST API. We are currently auto-generating those ranges instead of getting them from the real data.

Thus this can sometime lead to bad ranges leading to no results.

You best option currently would be to use the numericRefinementList that allows you to provide manual values for the ranges along with start/end bounds.

If you already know what price ranges you want, that's the way to go.

We will upgrade those numeric ranges widgets soon to make it clearer.

I am gonna update the docuentation to show how to pass manual values to numericRefinementList, in the meantime use this:

```js
numericRefinementList({
  attributeName: 'price',
  options: [{
    name: 'less than 500$',
    end: 500
  }]
})
```

Etc..

**Comment by tecmusti** [comment]
Hi @vvo 
I am sorry but your solution is not better than priceRanges widget. 
For example;
There is an option for less than 50. This option is still being listed even there are no items less than 50 for current refinements.

**Comment by vvo** [comment]
Hi @tecmusti indeed this is a bug to me also. I created the relevant issue here: https://github.com/algolia/instantsearch.js/issues/1135

If you feel like contributing this would be a very good opportunity, I linked the relevant code.

**Comment by vvo** [comment]
Thanks a lot @tecmusti for all the feedback and bug reports!
