### ISSUE TITLE
Save a search as a bookmark

### ISSUE THREAD

**Issue by chrisvidal** [algolia/instantsearch.js#1159]
We need to be able to save a user search and save it in some format so that the user can use it for later. 

Any way to achieve this would be nice ?

**Comment by chrisvidal** [comment]
ok, i guess i could use the default parameters to play a saved search by the user
https://community.algolia.com/instantsearch.js/documentation/#default-filters

**Comment by bobylito** [comment]
Hi @chrisvidal 

You should use the "url sync" mechanism. This will make your url update as the parameters of the search are updated. Those url can then be bookmarked. [https://community.algolia.com/instantsearch.js/documentation/#initialization](In the documentation), there is a paragraph on how to get started with this mechanic.

**Comment by chrisvidal** [comment]
Thanks @bobylito 
i thought about that at first, but i am maintaining 2 index search at the same time on my screen.
Meaning that the user can switch from search in an index A to an index B, with different filters and different results kind of object.

When i use the url sync, i didnt find a way to sync the url with my switch

**Comment by bobylito** [comment]
@chrisvidal : Are you using two instantsearch instances? Or are you using a widget to switch the indices?

**Comment by chrisvidal** [comment]
Yes im using 2 instances of instantsearch.
then in one instance of of them , i implement the searchFunction(helper) like this :
````javascript
searchFunction: function(helper) {
var query = companiesSearch.helper.state.query;
projectsSearch.helper.setQuery(query);
projectsSearch.helper.search();
helper.search();
}
````

Regarding my index switch, im using a simple form select with 2 options representing my index and then i switch and render the layout accordingly to the selected index using the same input type search, shared by the 2 instances of instantsearch.

**Comment by bobylito** [comment]
That's smart!

Maybe the [URL functions](https://community.algolia.com/algoliasearch-helper-js/reference.html#url) from the helper can help you.

One way or another you'll have to implement something similar to the url sync on your side. Here is [the source code](https://github.com/algolia/instantsearch.js/blob/develop/src/lib/url-sync.js) for reference.

**Comment by theShiva** [comment]
Hi @bobylito 

I looked at the [documentation link you provided - `options.urlSync`](https://community.algolia.com/instantsearch.js/documentation/#initialization), but couldn't tell, hence asking here.

Is it possible to implement this in a static site also? I have a static hugo site - [pawpurrazi.com](https://www.pawpurrazi.com/) - hosted on Netlify and am exploring search options for this, and Algolia was recommended.

I want to be able to display a search screen and allow user to select tags and/or categories from it. Once a user clicks search, I was the search parameters to be in the URL, so that if they bookmark it and revisit the query will be re-executed.

Example: If user puts "cat videos" in search box, which would eventually lead to [some of the videos listed here](https://www.pawpurrazi.com/tags/cat-videos/) , the URL should have something like https://www.pawpurrazi.com/search?q=cat%20videos and if they click this url again, the search should be re-executed and results displayed.

Thank you!

**Comment by iam4x** [comment]
Hello @theShiva this exactly the use case of the `urlSync` parameter that you set to `true` 👍 

You can see it implemented in the Airbnb demo: https://community.algolia.com/instantsearch.js/v2/examples/tourism/
