### ISSUE TITLE
Add examples to documentation

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#1167]
Let's provide some samples on codepen, that we can reference to our users (and later integrate in our documentation)

- [ ] Switching the index after instanciating instantsearch.js
- [ ] Set queryParameters in the initialization method
- [ ] Programmatically hide / display widgets depending on the results

**Comment by bobylito** [comment]
Thanks @maxiloc for moving those issues here. 👍

**Comment by bobylito** [comment]
I'm digging this issue :)

Since now we have a codepen account, let's create them there. It would be good to have those samples as I often feel the need to provide an example to our users on support but I feel like we do them over and over again.

Also let's edit @maxiloc first entry to keep track of those samples. :)

**Comment by vvo** [comment]
Our guide in react-instantsearch will cover all those aspects
