### ISSUE TITLE
Slider issue on click

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#120]
When clicking inside the slider (instead of drag and dropping) there is a js error

**Comment by pixelastic** [comment]
What I found is that clicking in the slider should add a class to the handle but fails because the reference to the handle (`data.handles[0]`) is `undefined`. 

As this is using a forked version of nouislider, wrapped in our own React component widget I kind of lost the track of the origing of it. Maybe someone more used to the slider could have a look?

**Comment by vvo** [comment]
Yes I will issue should be in my nouislider fork I guess

**Comment by vvo** [comment]
@pixelastic I know it feels weird but we should let opened issues opened until they are part of a release (and they will be auto closed when merged on master). That's ok for this one yes

**Comment by pixelastic** [comment]
Oh, ok, I wasn't aware of that.
