### ISSUE TITLE
write a react-native example

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1241]
Can we use react-instantsearch with react-native? This should be doable. Try to do it and see what happens.

If it works then write a documentation page showing how to do it/showing it works.

**Comment by mthuret** [comment]
Just played a little bit with react-native, here the list of what I observe for it to work: 

* [ ] we need a proper interface that will expose only connectors 
* [ ] we need an InstantSearch version that will use the algoliasearch for react-native client
* [ ] currently we are using `process.nextTick` on the createWidgetsManager (for update). It needs a polyfill on the react-native side in order to work.

**Comment by vvo** [comment]
Nice!

As for process.nextTick usage, I am not even sure this is needed/consequences versus a simple setTimeout(fn, 0). I would go for the later to ease the work

Being able to use react-instantsearch (connectors + `<InstantSearch>`) on react-native on day one would be awesome news!

**Comment by vvo** [comment]
As for the interface we expose, we had some discussion, we could do this:

```js
import {connectRefinementList} from 'react-instantsearch'; // platform agnostic
import {InstantSearch, RangeSlider} from 'react-instantsearch/dom'; // platform specific
import {InstantSearch} from 'react-instantsearch/native'; // platform specific
```

`InstantSearch` being platform specific because of the need to have a different algolia http client instantiated. And ultimately things like urlSync=true and createURL may not be working nor have the good semantics for a native platform (where we would maybe only talk about "routing" rather than url, dunno here).
