### ISSUE TITLE
RefinementList/Menu: allow to provide manual values

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1246]
One thing people struggle a lot with is being able to create a RefinementList or a Menu using manual values instead of the API ones.

We need to be able to easily answer the "I want to create a menu with those 5 colors in it, I have 10 colors in my index".

There might be other widgets where this makes sense, have a look.

**Comment by bobylito** [comment]
So this static list would not use the dynamic list of values from the server? Is creating a new connector/widget could be an option?

I had a user who wanted the static because it was not sure that the values he was interested in would be in the list returned by the engine. What are the other cases where we would like to have a static list of facet refinements?

**Comment by vvo** [comment]
cc @Shipow you had the issue at some point, you wanted to create a manual list for http://searchstone.io/

**Comment by vvo** [comment]
Actually this can be done using a connector again and providing the right set of items. So this is a guide issue.
