### ISSUE TITLE
Automatically deploy branches (= +PRS) to gh-pages for preview

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1274]
One thing we miss right now on the collaboration part is to be able to quickly visually see the result of a PR.

This could be solved by:
- deploy every opened PR to http://community.algolia.com/instantsearch.js/pr/#number/..
- it will make the PR docs accessible and possibly any change/new example. Much easier to comment/iterate
- we can use travis hooks on PRS, and reuse the gh-pages script (with some little tweaking so that we do not erase anything) to deploy
- after publishing, we should post a comment in the github issue
- then about cleaning merged PRS. When the v2 branch is built, we just list all closed PRS and we delete possible artifacts (or we use a github hook to do so, but never did that) from gh-pages

What do you think?

**Comment by bobylito** [comment]
Sounds great. Add a bot to post the link to the live version in github? :)

**Comment by vvo** [comment]
> Sounds great. Add a bot to post the link to the live version in github? :)

Oh yeah that also thanks, adding it

**Comment by bobylito** [comment]
I was sorta kinding but if you're up to it that would > 9000 :D

**Comment by vvo** [comment]
I so wish there was already easy services to do that, I could not figure out from circleci/codeship etc.. If they provided the whole workflow.

**Comment by hkdobrev** [comment]
I think [Heroku provides that out of the box](https://devcenter.heroku.com/articles/github-integration-review-apps). Not sure if this will work for you. We have this kind of solution even before Heroku has launched it. Using a single Apache wildcard vhost and an internal tool to listen to GitHub PRs and create a staging env for the branch - https://github.com/clippings/robot Before that we were using Docker containers for each branch, but it turned out to be quite a hassle.

**Comment by vvo** [comment]
Thanks for insights @hkdobrev, I think we will just use gh-pages since this is an OSS project this will do it.

**Comment by vvo** [comment]
Done using netlify, see https://github.com/algolia/instantsearch.js/pull/1929.

Although we could also do it for the develop branch, but for now we are good only doing it in v2 branch
