### ISSUE TITLE
When there is no refinement the name of the attribute stays in the URL

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#1286]
Where there is no refinement the attribute stays in the URL.

![attr-url](https://cloud.githubusercontent.com/assets/393765/18548383/adc13c80-7b48-11e6-9650-ddacf9e0cc8b.gif)

**Comment by mthuret** [comment]
While looking to correct this bug, I saw this comment on the RefinementList connector: 

 // Setting the value to an empty string ensures that it is persisted in
      // the URL as an empty value.
      // This is necessary in the case where `defaultRefinement` contains one
      // item and we try to deselect it. `nextSelected` would be an empty array,
      // which would not be persisted to the URL.
      // {foo: ['bar']} => "foo[0]=bar"
      // {foo: []} => ""

@vvo @Morhaus : do you remember the reason for that choice to persist empty value in the URL?

**Comment by Morhaus** [comment]
Let's say you set the default value of a `RefinementList` on the `"animals"` facet to `["cats"]`. When you first load the page, this default value won't be shown in the URL. The only way to deselect the `"cats"` value in this case is to explicitly set the `"animals"` facet value to an empty array. Just removing the entire facet value won't do, because then the default value will be selected again.

**Comment by mthuret** [comment]
Ok got it, thanks @Morhaus. So one thing we could do, is actually building the query without the facets that have an empty string value.

**Comment by vvo** [comment]
> The only way to deselect the "cats" value in this case is to explicitly set the "animals" facet value to an empty array

@mthuret In any way, we just need to keep this behavior, since it's feasible for people to do so, it's a feature (not just a weird edge case)
