### ISSUE TITLE
Synchronizing state of widgets that share the same attribute name 

### ISSUE THREAD

**Issue by mthuret** [algolia/instantsearch.js#1296]
Currently widgets that share the same attribute name doesn't share the same state. It means that if a user has two widgets for the same refinement, there will not be synchronized. 

Example : on the e-commerce demo we have two widgets to refine on prices. If the user selects a range on the prices list, the input range will not be automatically synchronized. Same thing for the url.

One solution would be that when the store is updated, widgets that share the same attribute name as the one that is responsible for the update, would have their state automatically changed as well. 
But this synchronization is currently not that simple because widgets doesn't necessarily share the same internal state. 

ex: taking the e-commerce demo again, for displaying prices, we use NumericRefinementList and InputRange widgets. The first one uses a "min:max" string as its internal, the seconde one uses an object with min/max values. 

@Morhaus  : when developing react-instantsearch, have you thought about this problematic and already have some ideas about it ?

**Comment by Morhaus** [comment]
Since the state is shared between all children of the InstantSearch component, different components *can* read and update the same state key. For instance, you can have two Pagination components at the same time. However, the format of their state should be normalized. In the case of NumericRefinementList and InputRange, I think it makes sense to pick one format for both.

However, for widgets that control the same refinement but have incompatible state, then maybe only one of those widgets should have a state at any point in time. I don't know of any such widget, so I'll use NumericRefinementList and InputRange as an example: when you select a value in a NumericRefinementList, the InputRange's state would get cleared, and vice versa. That would also mean using different state keys for both widgets.

**Comment by rayrutjes** [comment]
IMHO there should be only one source of truth which is the search state. Every widget should use that store for its own state. Widget internal state should only be some sugar to compute values but should always be directly bound to the search state.

**Comment by Morhaus** [comment]
See https://github.com/algolia/instantsearch.js/issues/1170

**Comment by rayrutjes** [comment]
Just took a look @Morhaus thx for pointing that out.

I think the solution implemented in #1170 brings more problems than it actually solves. 
It makes reasoning about widget states difficult.

Regarding the `currentRefined` widget, if it depends on other facets, then it should reference those facets and react on their changes.

It could even just use the attribute name for the display and let users provide an array of `attribute => label` for the display, and extract the refined values from the helper's state. IMHO that is the way to go about it.

Not sure if I'm missing something here @Morhaus

**Comment by Morhaus** [comment]
There are a lot of other features which depend upon this change. Default widget state/global state listener/virtual widgets (if they make it in) and I might be forgetting some.

Regarding the currentRefinedWidget, you cannot infer what actions resulted in given helper  state just from looking at its serialized representation. You can keep track of those actions, but without persisting them in the URL, refreshing the page will break the widget.

I agree that the current solution adds a layer of indirection that might seem unnecessary at first, but I don't see a better way to achieve the current set of features. The approach you're proposing is what I went with at first, before running into the issues I've described in #1170.

**Comment by rayrutjes** [comment]
> Regarding the currentRefinedWidget, you cannot infer what actions resulted in given helper state just from looking at its serialized representation.

Could you give an example?

What is it you call `virtual widgets`? widgets that have no UI? 

Regarding default widget state, IMHO widgets should take their state from the helper. When no state matched, then it can suggest its own default state but set it on the helper, not just internally.

**Comment by Morhaus** [comment]
Hey @rayrutjes, sorry for the delay.

> Could you give an example?

The issue we previously had with the currentRefined widget in InstantSearch V1 is that it had to infer which refinements were applied only from the SearchParameters. While this is possible, the result isn't always very human friendly. See the first example of #1170. Now, using only the SearchParameters, the widgets we currently have could still infer and declare their current filters from the SearchParameters.

The issue arises when two or more widgets operate on the same part of the SearchParameters, for instance a numeric refinement on the price facet. Should interacting with one widget affect the other as well? When a numeric refinement is set, should we show a current filter for both widgets? 

> What is it you call virtual widgets? widgets that have no UI?

Virtual widgets are widgets that are declared in JSX but have no DOM representation. They only exist to provide a nice way to interact with the underlying SearchParameters using the same interface as normal widgets.

> Regarding default widget state, IMHO widgets should take their state from the helper. When no state matched, then it can suggest its own default state but set it on the helper, not just internally.

We don't want default state to directly affect the helper's state, because default state should not appear in the URL. Also, we're mostly using the `SearchParameters` internally anyway, since we heavily rely on immutability in order to batch state modifications. We're only really using the helper's `searchOnce` method.

**Comment by vvo** [comment]
To sump up here, I think this is a good discussion starter. Today the drawbacks of our widget's states + search parameters state are:
1. syncing two widgets is not working
2. creating your own widget is hard
3. code complexity introduced by multiple stores

1. I am sure we can workaround this

2. This is an issue, but if we provide all the needed connectors there should be almost no cases where you need to actually create a completely new widget, only connect

3. This is an issue clearly.

I am all in if anyone have clear ideas on how to solve this, even if it requires rewriting/deleting some good code. Today the state is that we are multiple people concerned by this issue, but we will only fix it once we know what to do about it and open a PR.

**Comment by joelm10** [comment]
could you not implement a single store at top level for the search result, and propagate this down as needed to child widgets?

Sounds like a possible good use of redux store?

I'm doing some initial investigations on this for my own project

**Comment by vvo** [comment]
@joelm10 Sorry for late answer, could you detail a bit more what you have in mind and what where you trying to achieve that would require synchronising widget states?
