### ISSUE TITLE
Mounting and unmounting components

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1340]
What happens when we mount/unmount components?

Example: a select box that will show/hide different RefinementList.

1. Is it working?
2. To which extent? Are the refinements kept or removed? If it's not clear right now, what should we do.

**Comment by bobylito** [comment]
Well it's working to the extent of the behavior of the component when unmounting. The state is stored in the store and thus it is decoralated from the component state. On the other hand if the component implement a clean up on unmounting then it will be cleared. And it would make sense to clean up because there is no mean to opt out part of the store. Also, applying some ui filters that were hidden by a user action is not a straightforward behavior. I mean you hide something and yet it stills applies is confusing, right?

**Comment by vvo** [comment]
> And it would make sense to clean up because there is no mean to opt out part of the store. Also, applying some ui filters that were hidden by a user action is not a straightforward behavior. I mean you hide something and yet it stills applies is confusing, right?

Yes I would say this should be the default behavior. But at the same time I would understand people doing things like show/hide only for UI simplification purposes, like implementing collapsible facets/accordion that would ultimately not render the RefinementList while the refinements would still be applied.

Maybe for now what we could do is only document and precise the current behavior in the guide? Then given user feedbacks we will decide what is the best behavior to implement?

**Comment by vvo** [comment]
Moved to #1459
