### ISSUE TITLE
Allow pagination to hide when there is only one page

### ISSUE THREAD

**Issue by Sammaye** [algolia/instantsearch.js#1402]
Quite a simple one, when there is only one page hide the pagination else it looks a little silly just sitting there on it's own as a single box saying "1".

**Comment by vvo** [comment]
Hi, you can do a simple hide pagination widget: https://github.com/algolia/instantsearch.js/pull/1049#issuecomment-222927757

**Comment by Sammaye** [comment]
Ah will need to take a look at that thanks

**Comment by Sammaye** [comment]
Okay, that works, but seem really messy to have to add a custom widget just to hide the pagination on single page results.

**Comment by vvo** [comment]
@rayrutjes We are open to discussion for an API that does not requires adding more classnames. The issue is that the more state we inline into the classes API, the less easy it is to document it.

Also utlimately this is a design decision but if you hide the pagination when there's only one page, you do provide less context for the user. If there's no pagination on a webpage (or if the pagination is hidden/shown given some context I do not decide), then the user might think "Well, maybe there's more result, maybe that the only page, but I can't tell it because I don't know how this page is built".

**Comment by Sammaye** [comment]
TBH showing a lonely "1" on the page is actually proven (form my own testing) less contextually useful to the end user

**Comment by LuckyJack101** [comment]
Found another solution - I'm using Vue, but should be doable across the board.

1. Use ais-stats to get number of pages
```vue
<ais-stats>
  <template slot-scope="{ nbHits, page, nbPages }">
    <span
      class="-s-results-found"
      v-html="getResultText(nbHits, page, nbPages)"></span>
  </template>
</ais-stats>
```

2. As you run the function to generate the result text, you can decide to show the pagination
```js
getResultText(nbHits, page, nbPages) {
  // Decide to show pagination
  if (nbPages > 1) eventBus.isShowingPagination = true

  // Return text
  let text = ''
  if (nbHits === 0)
    text = `<span class="-s-hidden-good">W: </span>No products found`
  if (nbHits === 1)
    text = `<span class="-s-hidden-good">W: </span>${ nbHits } product found`
  if (nbHits > 1)
    text = `<span class="-s-hidden-good">W: </span>${ nbHits } products found`
  if (nbPages > 1) text += ` - Page ${ page + 1 } of ${ nbPages }`

  return text
}
```

3. Now you can show/hide your pagination conditionally
```vue
<ais-pagination
      :show-next="false"
      :show-previous="false"
      :class-names="{ 'ais-Pagination': '-s-srp__pagination' }"
      :class="{ '-s-hidden-good': !isShowingPagination }"
      @page-change="onPageChange"/>
```

Best of luck
