### ISSUE TITLE
defaultSelectedItems for MultiRange in react-instantsearch

### ISSUE THREAD

**Issue by harshmaur** [algolia/instantsearch.js#1408]
Hi, 

I messaged on gitter regarding this. 

Pasting all the content. 

I want to predefine the numeric refinements in `MultiRange` just like `defaultSelectedItems` in `RefinementList` 

```jsx
const VirtualRefinementList = RefinementList.connect(() => null);

{/*We create default refinements like this*/}
<VirtualRefinementList attributeName="category_slug" defaultSelectedItems={[“mobiles"]} />

{/* how to create default numeric refinements 
 pseudo code… or it can be a VirtualMultiRange
*/}
<VirtualRefinementList attributeName=“price" defaultSelectedItems={[>15000]} />
```

**Comment by harshmaur** [comment]
Really need help with this. @vvo

**Comment by vvo** [comment]
@harshmaur can you try: `defaultSelectedItems=":50000"`?

This is currently a #fail of our API, too hard to understand and not documented.

Sorry for late reply.

**Comment by harshmaur** [comment]
Hi @vvo Thanks you for reply. I will test it out and get back to you. Can you tell me how I would do >= or <= with this syntax?

**Comment by harshmaur** [comment]
Using `<VirtualRefinementList attributeName="price" defaultSelectedItems=":50000" />` gives error `getSelectedItems(...).map is not a function(…)`

**Comment by mthuret** [comment]
Hello @harshmaur, if you want to have a default selected range using the MultiRange, you could try with `defaultSelectedItem` instead of `defaultSelectedItems` (little typo here, sorry). This syntax works for a MultiRange, not a RefinementList. The RefinementList expects an array of default items. 

If I look to your example you would have something like:

`<VirtualMultiRange attributeName="price" defaultSelectedItem="150000:" />`

Also, the defaultSelectedItem you choose should match with one of the item manually declared using the `items` props. 

Full example with a MultiRange:

```js
<MultiRange attributeName="price"
                items={[
                  {end: 10, label: '<$10'},
                  {start: 10, end: 100, label: '$10-$100'},
                  {start: 100, end: 500, label: '$100-$500'},
                  {start: 500, label: '>$500'},
                ]}
                defaultSelectedItem="500:"
/>
```

If I wanted to select the "<10" by default, I would have written: `":10"`

Definitely our doc should be improved here. 

Let me know if it works better.

**Comment by harshmaur** [comment]
Got it works now!! You can close the issue if you want to.

**Comment by vvo** [comment]
Let's close this, we will need to get back at how we provide defaultRefinements in a consistent way still.
