### ISSUE TITLE
RefinementList: Avoid showMore for show nothing

### ISSUE THREAD

**Issue by Kikobeats** [algolia/instantsearch.js#1428]
![](https://d17oy1vhnax1f7.cloudfront.net/items/3u2W2J282H3a0C1K1e27/Screen%20Recording%202016-10-17%20at%2007.03%20pm.gif?v=e3b8553a)

**Comment by vvo** [comment]
Thanks, this is a bug (want to fix it? :D)

**Comment by Kikobeats** [comment]
@vvo I wanna, but I actually don't know how to setup `react-instantsearch` on local with live-compile for fix this

**Comment by vvo** [comment]
https://github.com/algolia/instantsearch.js/tree/v2#development should be sufficient, did you try?

**Comment by Kikobeats** [comment]
yes, but I mean, in my code I have `require('react-instantsearch')`.

Could be possible have a local copy of `react-instantsearch` and compile it every time that I make a change to be how the changes affect to my code?

**Comment by vvo** [comment]
@Kikobeats Not so easy to do, easiest would be to use our dev environement, take any live example and fix it from there (or use npm run dev, it's a live reload jest unit test env).

We currently do not have an npm run build:watch so maybe that's what you would require? So that you could just:

- clone v2 branch of instantsearch.js
- yarn
- npm link
- npm run build:watch

Then in your project:
- npm link react-instantsearch

Would that work for you?

**Comment by bobylito** [comment]
What should be the behavior? I was thinking that if I activated the option I would maybe not get that why the button would disappear. Maybe instead of hiding the button, we should disable it when item count < limitMin?

**Comment by Kikobeats** [comment]
@bobylito yes. One option could be add a `disabled` class under `count < limitMin`

**Comment by vvo** [comment]
Looks good as a solution

**Comment by vvo** [comment]
Moved to #1455
