### ISSUE TITLE
instantsearch.js overriding maxValuesPerFacet

### ISSUE THREAD

**Issue by imshinto** [algolia/instantsearch.js#1441]
InstantSearch.js is overriding the maxValuesPerFacet to 10. PFB the same :-
https://github.com/algolia/instantsearch.js/blob/8d4678c3583fbd59196cfcb80906264d10368208/src/widgets/refinement-list/refinement-list.js#L72:L84

So when business user decides to change this value through the Algolia Dashboard it doesn't work, since always the client code overrides the settings in the values set in Dashboard.

This should be removed from instantsearch.js and the business user should be able to adjust these values dynamically through the Algolia Dashboard.

Thanks,
Shinto

**Comment by imshinto** [comment]
has this been fixed ?

**Comment by vvo** [comment]
@imshinto Thanks for opening this issue.

Right now this is not easily solvable. This would require a new option value in limit= so that we understand we should not send any limit parameter.

For this to work for now you will have to control the limit parameter from the frontend. Indeed it means you won't be able to use the dashboard to control the number of facet values being displayed. The widget was never designed with this usecase in mind, for now.

But as we are revamping instantsearch.js, this is a good indicator that we should be able to do what you want.

**Comment by bobylito** [comment]
Closing for now. There is too much mechanics involved in the front-end to actually control of the number of facet from the dashboard.
