### ISSUE TITLE
refinements must still be applied even when Component is unmounted

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#1459]
Following #1340

**Comment by harshmaur** [comment]
Hello! 

I figured that in order for url to sync with the refinements, they need to be in mounted state. 

If we have a dual page layout where the listing page and the filters pages are different, you cannot expect the listing pages to have refinements mounted, the only way to find the state is through url. 

However, i would prefer it at an option for the developer if he wants to create state from the current url and pass it when he wants to.

**Comment by vvo** [comment]
Hey @harshmaur following this I am wondering if a good solution for you right now could be to use VirtualRefinements so that your refinements are always applied even when unmounted.

Basically not only you have to use rendering refinements but also also have virtual refinements mounted so their state is always applied.

This should work. Let me know.

**Comment by harshmaur** [comment]
Hmm, Makes sense. I will try to implement this and get back to you on this.

**Comment by vvo** [comment]
Our answer to this will not to clean then but actually always keep the refinements even when unmounted, we will work on that later on.

**Comment by harshmaur** [comment]
But the refinements need to be initialised at some point. In my specific use case, I initialise it when I click on it, however it changes when there is a change in the refinement. 

I havent quite got time to implement the solution as I know this solution will give me problems on the listing page as there will be refinements present on the url but none of the refinements would be mounted on the listing page since there is no space for filters.

**Comment by vvo** [comment]
> But the refinements need to be initialised at some point. In my specific use case, I initialise it when I click on it, however it changes when there is a change in the refinement.

I am not sure to understand your comment compared to the solution of "as soon as a widget is initialized, if you refine two values and then unmount the widget, we will keep the refinements".
