### ISSUE TITLE
Wrong currentRefinements values when using starRating widget

### ISSUE THREAD

**Issue by JanPetr** [algolia/instantsearch.js#1567]
**Do you want to request a *feature* or report a *bug*?**
*Bug*

**What is the current behavior?**
When refining with `starRating` widget, and select for example **2 stars & Up,** in currentRefinemens widget are displayed 4 refinemens even though I selected only 1 - **2 stars & Up**.
And the current refinement values are not formatted into starts - I guess they should.

Screenshot:
<img width="460" alt="screenshot 2016-11-16 17 40 42" src="https://cloud.githubusercontent.com/assets/1058144/20356128/e32ddf2a-ac23-11e6-81ba-fcd4f1475514.png">

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**
https://jsfiddle.net/JanPetr/97scwnf4/ - try to filter **2 stars & Up**

**What is the expected behavior?**
Display only the selected refinement in currentRefinements widget and formatted into stars if possible.

**Comment by vvo** [comment]
@JanPetr This is a good idea but non easily fixable in instantsearch V1.

This has to be fixed in userland in ISV1 (like integrations are doing sometime) because the state exposed by instantsearch is not linked to the UI (stars) but to Algolia refinements semantics (here multiple numeric filters). So we have no way to know in currentRefinedValues that this is actually the star widget that constructed this refinement. See the underlying code here: https://github.com/algolia/instantsearch.js/blob/36bee1ef2fc54dc24d4476930f0de71e9e8f04ee/src/widgets/star-rating/star-rating.js#L170

This is getting better in react-instantsearch and is a good reminder on how the state should look like for us to be able to easily
