### ISSUE TITLE
BC break in 1.8.15 in currentRefinements + toggle

### ISSUE THREAD

**Issue by JanPetr** [algolia/instantsearch.js#1569]
**Do you want to request a *feature* or report a *bug*?**
*Bug / BC break*

**What is the current behavior?**
In version 1.8.14 in toggle widget when the `value.on` is **-2** the currentRefinements widget correctly displays "-2".
In version 1.8.15 the currentRefinements widget displays **\\-2**. Might be because of [this](https://github.com/algolia/instantsearch.js/pull/1551/files#diff-f30be47b27731dbff3e3402f27f81c1dR23)?

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**
1.8.14 - https://jsfiddle.net/JanPetr/oynhy43u/2/
1.8.15 - https://jsfiddle.net/JanPetr/oynhy43u/1/
Try refine **On Stock** products on both versions and see current refinements.

**What is the expected behavior?**
To be honest I'm not sure which version is correct. I'd expect the one without `\`

**Comment by vvo** [comment]
Yes the value is escaped to allow negative numeric in toggles (#1551). Do you think we should consider this as a BUG? In your example the rendering is cryptic, in reality you would put a label in currentRefinedValues instead of displaying the on/off refinements (which most of the time won't be meaningful labels).

But maybe you mean it's a B/C because people could be relying on this value not being escaped before?

**Comment by JanPetr** [comment]
Yes, actually putting the label is the issue. Snippet of production code which broke:

```js
search.addWidget(instantsearch.widgets.currentRefinedValues({
	container: '#ais-filter-tags', 
	transformData: {
		item: function (item) {
			if (item.name == "-2") {
				item.name = 'On Stock';
			}
			return item;
		}
	}
}));
```

To make it properly they had to change the condition to `if (item.name == "\\-2")`.

I'm OK with going with escaped version. More I wanted to point out the BC break.
