### ISSUE TITLE
ScrollTo+Pagination: Introduce a small delay before scrolling top

### ISSUE THREAD

**Issue by redox** [algolia/instantsearch.js#1635]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

When using both the `ScrollTo` and `Pagination` widgets, it scrolls so fast to the top that it's actually pretty confusing to understand that your click worked. I would expect a visual feedback explaining my page 2 will load (by selecting it for instance) before it actually scrolls.

Of course, it's more complex that just adding a `setTimeout` in the `ScrollTo` component because we would like to select the next page before the API actually answers. Something like:
 - click on the next page
 - change the selected/highlighted page number (before the API comes back with the new page)
 - query the API
 - scroll top

Would love to hear what you guys think. cc @Shipow @LucasC

**Comment by vvo** [comment]
Not an easy topic indeed, this is also the current behavior in instantsearch.js V1 (the one that is surprising).

I have no silver bullet for this and what you propose @redox can be disturbing as well I guess since the changes in pagination UI are very small (page change) compared to the fact that the whole page is gonna be updated after scrolling top.

What could work is a very fast/nice fadein fadeout effect. And having the API semantics to be able to trigger that.

**Comment by jdylanmc** [comment]
I would like some easing options and delay.  E.g., perform a linear scroll over 1500 MS.

This has my vote!

**Comment by jaskirk** [comment]
That will be useful! +1

**Comment by mthuret** [comment]
React InstantSearch has been moved here: https://github.com/algolia/react-instantsearch
This issue has either been rewritten or placed inside our backlog.
