### ISSUE TITLE
Default style: no default style for Highlight or Hits

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#1683]
It's a bug.

**What is the current behavior?**
Right now, it applies the default style of the browser even when using itemComponent option.

![screenshot 2016-12-07 11 40 41](https://cloud.githubusercontent.com/assets/393765/20964501/1395e776-bc72-11e6-8b37-274c2606621f.png)

**What is the expected behavior?**

It should apply at least:
 - the same font as the widgets
 - a proper style for highlight

**Comment by vvo** [comment]
What we decided so far:

- add an .ais-InstantSearch__root class name on the main container
- set a default font-family on .ais-InstantSearch__root (sans serif, more?)
- style the default highliting class names so highliting looks good by default
- add some CSS to the getting started tutorial so that if a user follows it, the products are looking good by default

Thanks @bobylito for bringing that up, details like that are key to a great experience
