### ISSUE TITLE
Prevent sort RefinementList onChange

### ISSUE THREAD

**Issue by Kikobeats** [algolia/instantsearch.js#1734]
Not sure if is possible, but desirable in my case.

Could be possible prevent put on top of the list the marked items?

![](https://d17oy1vhnax1f7.cloudfront.net/items/2J2x1D2V020s2M2z0L0I/Screen%20Recording%202016-12-12%20at%2012.11%20pm.gif?v=3e287e0e)

My RefinementList implementation is [here](https://github.com/windtoday/windtoday-app/blob/master/src/app/RefinementList/index.js).

**Comment by bobylito** [comment]
Thanks @Kikobeats for the issue. This is done when sorting the values. This is not possible to change the order without using a connector.

**Comment by vvo** [comment]
@bobylito @mthuret Do you think we should provide a generic entry to reformat the data? Not a sortBy, not a map. Just a simple method where you can either filter/reorder as you want based on the provided props.

I know we took the path to say "widgets => no options". But since we also made the move from "no css => good css", if we actually want people to use a bit of our widgets, maybe we could be a little bit more flexible here?

We do have SOME options (limit, showMore..). We just need to find the right set of options that handle many use cases, sortBy is limiting, let's make it a complete reduce (well, you will still need to send some array items, but you can do whatever you want with them).

**Comment by mthuret** [comment]
I think this a good idea to bring some flexibility. 

With this, a widget user will also be able to push some pre-defined data. So actually there's is several use case for it. 

I didn't get this part though: 'default transformProvidedProps in lists should be alpha + count instead of isRefined + alpha + count?'?

**Comment by vvo** [comment]
> I didn't get this part though: 'default transformProvidedProps in lists should be alpha + count instead of isRefined + alpha + count?'?

Today the default sort we do in lists is: if it's refined, it's on top, then we use alphanumeric + count sort. We should maybe just use alphanumeric sort so that users are not surprised..?

**Comment by mthuret** [comment]
Maybe on the default behavior we can check before (with CSE?) what would be the one we want to push for? As long as we can override it, it should be fine, no?

**Comment by bobylito** [comment]
The facets are dynamic based on the result set. Removing `isRefined` means that the selected values may disappear, which is also confusing for users. I think that there is no perfect solution here, but at least end-users (not devs) will be less confused by moving values than disappearing values.

**Comment by bobylito** [comment]
Some thoughts on the topic:
 - the sort strategy depends, on the number of facet values. If you have few, you probably want  something static because there is little to no risk that the value will disappear. The opposite is true, if you are likely to loose the values you probably want to keep them
 - what if displaying the selected values in the list is not important? What if we could display them on top of the list, without altering the order to fit the need to keep the selected values on sight?

**Comment by bobylito** [comment]
> maybe we could be a little bit more flexible here?

👍  Sorting is at the fringe of the UI but not quite, imho.

**Comment by vvo** [comment]
> what if displaying the selected values in the list is not important? What if we could display them on top of the list, without altering the order to fit the need to keep the selected values on sight?

I thought about this also but displaying them on top of the list would do exactly what we do today no? Even if we show them inline (a bit like CurrentRefinements) they would still jump from the list to the top.

**Comment by vvo** [comment]
You can no do it with transformItems, see https://community.algolia.com/instantsearch.js/react/guide/Sorting_and_filtering.html#example
