### ISSUE TITLE
Injecting (prepend/append) results/hits

### ISSUE THREAD

**Issue by timkelty** [algolia/instantsearch.js#1769]
I am trying to prepend a "featured" item to my results.

I am able to do this with the hits widget's transformData option, except it seems this is done to late (only for the template), so pagination, totals, etc. are then all off.

Where/when can I inject a result into my search so that counts and pagination aren't thrown off?
Furthermore, using transformData causes it to be added on every paginated render, I only want it on the first.

**Comment by bobylito** [comment]
Hi @timkelty Thanks for opening this issue. All results should come from the engine because this is where all the counts are computed. You can do that directly in the engine. You have to procede in two steps:
 - add in your records a new boolean attribute 'featured'
 - configure the engine to bucket the featured records first (ordering the attribute descending)
![screenshot 2016-12-29 11 04 13](https://cloud.githubusercontent.com/assets/393765/21541435/99f2b312-cdb6-11e6-98a0-74bc3537ae3f.png)

**Comment by timkelty** [comment]
@bobylito Unfortunately what I'm trying to do is more complex than that.
More details here: http://stackoverflow.com/questions/37924976/instantsearch-js-hits-widget-transforming-data-on-refinement

Pretty sure to do this I need to perform 2 queries, which is fine - but the problem comes in how to merge the 2 results and maintain counts, paging, etc.
