### ISSUE TITLE
Highlighting for _snippetResult [react-instantsearch]

### ISSUE THREAD

**Issue by R4ph-t** [algolia/instantsearch.js#1776]
Hard to handle highlighting for **_snippetResult** values.  
The `<ais-highlight-`+`timestamp>` tag format makes things harder (than `<em>`) when you don't have a specialized component like the `Highlight` for `_highlightResult ` that can handle it.

**Comment by mthuret** [comment]
There's two options here to solve this: 

1. We create a new widget called `<Snippet/>` that has the same interface as the `<Highlight/>` one except that it will look for `_snippetResult` instead of `_highlightResult`. 

2. We add an optional prop `path` to the `<Highlight/>` component that allow a user to specify it's own path to the right structure. Default would be `_highlighResult`. 

I tend to prefer the first one, I think it's clearer: if you want to display a snippet, you use the snippet widget. WDYT @vvo and @bobylito?

**Comment by bobylito** [comment]
I vote for 1/ :)

**Comment by vvo** [comment]
1/ for sure
