### ISSUE TITLE
HTML encoding

### ISSUE THREAD

**Issue by ryanmitchell** [algolia/instantsearch.js#1778]
Hello

There could be a way around this, but any HTML encoded values (e.g. &pound;) are displayed as the encoded value, rather than the symbol they should be displaying (£).

To explain I have a value in my template of {{ text }} and that attribute in algolia contains an encoded value, then the encoded value is output rather than the symbol

Is there a way around this?

Thanks
Ryan

**Comment by bobylito** [comment]
Hi @ryanmitchell. Thanks for opening this issue. Have you tried with `{{{ text }}}`?

**Comment by ryanmitchell** [comment]
Thanks Alex - thats done the trick.

Apologies if that was obvious and I missed it.

**Comment by bobylito** [comment]
It was obviously not obvious :) Truth is I asked myself this many times ;)

**Comment by Haroenv** [comment]
@zeke, not sure what the issue is exactly (best to have a reproduction for that, using our template,available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js)), but does your `hits` have `escapeHTML: false`? That's required for us not to do escaping :)
