### ISSUE TITLE
Geo-search box widget

### ISSUE THREAD

**Issue by jaarkko** [algolia/instantsearch.js#1786]
In my opinion this is both a feature request and a bug.

At the moment we cannot use instantsearch.js to make geo-search with an easily defined. Changes Search parameters don't seem effect once mounted properly and changing the latlng wont give me proper results.

Does anyone have a way to use instantsearch that:

1. geocodes a places location
2. adds that as a center on the map
3. Shows results based on _geoloc

Both versions of instantsearch are effected.
- react-instantsearch
- instantsearch.js

**Comment by bobylito** [comment]
Have you tried our [instantsearch widget for Algolia places](https://community.algolia.com/places/documentation.html#instantsearchjs)?

**Comment by vvo** [comment]
@jaarkko On top of what @bobylito said, one thing that would help us understand what you want to achieve would be you mocking an interface you would like to build with the behaviors it should have.

Then starting from that, I believe we could extract both widgets and guides that would help others.

To start working on this we will need a more detailed explanation on what exactly you would like to be able to do with instansearch projects. Thanks!

**Comment by jaarkko** [comment]
So, decided to use Vanilla Algolia JS.

End result: meetingpackage.com/search

Very happy with the result.

Probably cant take instant search into such complexity. It is good as it is.

@bobylito instantsearch widget for Algolia places didnt work properly with complex faceting etc.

**Comment by vvo** [comment]
Ok we are good if you managed to do what you wanted.

**Comment by johnmpotter** [comment]
Hey there Algolia Team, I've been following this issue because i've come across a similar need in my app. I'm using the react-instantsearch library and I'm in love with it, but this is one of the pieces I found missing. Although my application is slightly different, it's the same feature set that @jaarkko ended up implementing at [meetingpackage.com/search](meetingpackage.com/search). 

1. The ability to filter results by a location input (with location autocomplete)
2. The ability to filter results by a map bounding box (eg. "Search within map")

Using your [Tourism demo](https://community.algolia.com/instantsearch.js/react/examples/tourism/) as an example, a user would have a hard time finding a place to stay if they couldn't filter by location.

I've included a mockup of how we're planning on implement it. For the time being, i've just removed the geo search feature hoping you guys would build a react widget for it. 🙂

Do you think this is something that would fit into the scope of the react-instantsearch library?

<img width="1194" alt="screen shot 2017-01-18 at 8 29 08 am" src="https://cloud.githubusercontent.com/assets/5359194/22072925/c35776a0-dd58-11e6-8a4b-35b224a1443c.png">

**Comment by vvo** [comment]
I think we should first do guides about doing this. both instantsearch.js and react-instantsearch have geo abilities API features. We might want to go further and maybe also provide full fledged widgets. This is a good subject to dig in and I'll ensure we do dig it in instantsearch.js and react-instantsearch soon. Thanks!

**Comment by vvo** [comment]
> @bobylito instantsearch widget for Algolia places didnt work properly with complex faceting etc.

@jaarkko Could you maybe do a more detailed feedback on Algolia places repository and help us make this better? Thanks!

**Comment by bobylito** [comment]
Yes @jaarkko I'm very interested in your feedback on the topic :)

**Comment by marktani** [comment]
>  both instantsearch.js and react-instantsearch have geo abilities API features

Can you elaborate? I couldn't find any widget fitting this description here: https://community.algolia.com/instantsearch.js/react/widgets/

Appreciate any pointers in this matter :slightly_smiling_face:

**Comment by vvo** [comment]
@marktani for instantsearch.js: https://community.algolia.com/places/documentation.html#instantsearchjs

for React InstantSearch: https://community.algolia.com/instantsearch.js/react/guide/Search_parameters.html while injecting geo parameters from Algolia: https://www.algolia.com/doc/guides/geo-search/geo-search-overview/

**Comment by marktani** [comment]
Thanks, I'll take a look :)
