### ISSUE TITLE
IE >= 8 Support

### ISSUE THREAD

**Issue by redox** [algolia/instantsearch.js#18]
> Since Babel assumes that your code will be ran in an ES5 environment it uses ES5 functions. So if you're using an environment that has limited or no support for ES5 such as lower versions of IE then using the es5-shim along with the Babel polyfill will add support for these methods.

https://babeljs.io/docs/advanced/caveats/

**Comment by vvo** [comment]
So I tested it and even the simple class construct does not works when compiled, because it uses Object.defineProperty.

We can either:
1. drop every ES2015 line and do it the old way
2. embrace ES2015, ask our users to include es5-shim if they plan to use instantsearch.js in legacy browsers

I would go for 2 because we do not want to wake up the 1st january of 2016 and think "GOD I did no write a single ES2015 line in 2015..".

The helper and search client are already IE8+ compatible. Which mean that if you really really want to support IE8 because you are a big company then you can just roll everything yourself or include es5-shim.

I already asked once a user to include es5-shim and sham and it worked flawlessly (when the helper was not IE8 compatible)

What do you think?

**Comment by vvo** [comment]
IE9 works well

**Comment by redox** [comment]
I didn't dig a lot into it, but they seems to mention a "loose mode".

> By default, when using modules with Babel a non-enumerable __esModule property is exported. This is done through the use of Object.defineProperty which is unsupported in IE8 and below. A workaround for this is to enable loose mode - modules.

I thought that was enough to support IE8 but maybe I don't see get all of it.

**Comment by vvo** [comment]
Just tried with loose mode, still failing.

The web page is not really well done but they do state this:

```
Since Babel assumes that your code will be ran in an ES5 environment it uses ES5 functions. So if you're using an environment that has limited or no support for ES5 such as lower versions of IE then using the es5-shim along with the Babel polyfill will add support for these methods.
```

Which to me means that we do need es5-shim etc.. and even with that, some weird edge cases will not work:

```
Internet Explorer

Classes (10 and below)
If you're inheriting from a class then static properties are inherited from it via __proto__, this is widely supported but you may run into problems with much older browsers.

NOTE: __proto__ is not supported on IE <= 10 so static properties will not be inherited. See the protoToAssign for a possible work around.

For classes that have supers, the super class won't resolve correctly. You can get around this by enabling loose mode for classes.

Getters/setters (8 and below)
In IE8 Object.defineProperty can only be used on DOM objects. This is unfortunate as it's required to set getters and setters. Due to this if you plan on supporting IE8 or below then the usage of getters and setters isn't recommended.

Reference: MDN.

Modules

By default, when using modules with Babel a non-enumerable __esModule property is exported. This is done through the use of Object.defineProperty which is unsupported in IE8 and below. A workaround for this is to enable loose mode - modules.
```

**Comment by vvo** [comment]
I feel this will slow us down if we try to keep babel AND support IE8 and make it work.

So either we drop ES2015 or we state that you need es5-shim/sham which should be acceptable.

**Comment by redox** [comment]
:+1: I'm happy telling our customer to include es5-shim/sham, and keep writing ES2015 code :)
