### ISSUE TITLE
API Proposal: searchOnEmptyQuery: boolean

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#185]
```js
var search = instantsearch(appId, apiKey, {
  searchOnEmptyQuery: false
});
```

What this would do is not do any search query when the query is empty. This would allow people wanting to build things like https://github.com/algolia/instantsearch.js/issues/83#issuecomment-146159807 more easily.

What do you think?

**Comment by pixelastic** [comment]
Not sure this is the right approach. What this will do is keep displaying the last results when people will use backspace to delete their search term (because we won't fire a search on the empty query, so the last results will still be here).

I feel that what is needed for the linked use case is more a way of disabling the initial `search()` on the instantsearch instanciation. Something like `searchOnInit: false`. The search would then only be started on the first keystroke.

**Comment by vvo** [comment]
> What this will do is keep displaying the last results when people will use backspace to delete their search term

Yes indeed.

> I feel that what is needed for the linked use case is more a way of disabling the initial search() on the instantsearch instanciation.

The need is not just on first query, if you erase things like on jadopado.com then they still display the nice homepage (= no empty query).

So if we have `searchOnInit: false` we will still be able to do what we want (given we have events like #184) but we will do empty queries for nothing (and then hide the result).

**Comment by bobylito** [comment]
What about storing the content of the container, to display it back when there is an empty query?

**Comment by vvo** [comment]
> What about storing the content of the container, to display it back when there is an empty query?

I did not get what you propose.

**Comment by bobylito** [comment]
Initially there can some content where the hits will be displayed. For example you have a front page and some content, and you replace this content with the hits when the user start searching stuff. What about instead of just simply replace the content, we could store it and display it again when the search bar is empty?

**Comment by bobylito** [comment]
Shall we do that?

**Comment by vvo** [comment]
Yes if you agree on the [API proposal](https://github.com/algolia/instantsearch.js/issues/185#issue-110211771) then let's do it.

**Comment by bobylito** [comment]
Yes yes I do agree, it was just something to maybe add.

**Comment by bobylito** [comment]
After discussing with @vvo and @proudlygeek, this feature is not enough for what we want (which is jadopado like with the front page with content on empty string). It also brings discussion about wether or not jadopado is good search UX.

**Comment by vvo** [comment]
Yup, we should wait for a user to pop in here and say "Hey I need that". I bet :beers: on this :8ball:
