### ISSUE TITLE
Multiple instantsearch queryHook

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#1893]
When using multiple instantsearch (instantsearch with multiple index)

You have:
- several instantsearch instance (1 per index)
- 1 searchbox widget
- different hits widget for each instance

If you are using queryHook, the callback you give is call one time per instantsearch instance.
But I did not find a way to know which instantsearch instance is currently being "hooked".

Probably having the index name as one of the parameters of the hook would be better.

Right you kind of need to hack by creating several searchbox widget for each instance which is not the most logical.

**Comment by vvo** [comment]
Can you create a jsFiddle demonstrating the issue? I am not sure to follow, you can start from this: https://jsfiddle.net/j9nwpz34/

**Comment by maxiloc** [comment]
Here you go:

Let's say you want to query one index when query.length > 2 and another where query.length > 4

you do this: https://jsfiddle.net/ufycxbwv/ which require you to do two searchbox widget

I would prefer the following: https://jsfiddle.net/0gv52cfz/ where you have only 1 searchbox widget and 1 query hook for both

**Comment by vvo** [comment]
See this example for a way to do this: https://jsfiddle.net/ufycxbwv/3/

**Comment by vvo** [comment]
Also your first example was not working

**Comment by maxiloc** [comment]
Your example works but it's not very logical and not very intuitive:
I think this logic (inside the queryHook) would make more sense:  https://jsfiddle.net/0gv52cfz/.

Sidenote:
When doing this https://jsfiddle.net/ufycxbwv/  it wraps several time .ais-search-box which
is not perfect (I can open another issue for that if needed)

**Comment by vvo** [comment]
Thanks for all the feedback.

1. You cannot bind multiple searchBox to a single container, it has been discussed multiple times but in the end the "multi index search" can be achieved with very little code https://jsfiddle.net/j9nwpz34/. This will become the official way in the newly done website of instantsearch.js
2. Query hook has no knowledge of the index used. And a single instantsearch instance only deals with a single index.

To better understand what you want to achieve, we will need the concrete usecase rather than the implementation. In this very issue we are talking about implementations of your need but not the business/concrete usecase which we need. Getting the usecase will help us provide you maybe a better solution.
