### ISSUE TITLE
Support keyboard navigation on pagination

### ISSUE THREAD

**Issue by vinhlh** [algolia/instantsearch.js#1898]
**Do you want to request a *feature* or report a *bug*?**
Feature.
A best practice for page navigation 💃 
- Support enabled | disable mode.
- Support custom keys, default Left Arrow and Right Arrow.

**What project are you opening an issue for?**
- react-instantsearch

**Comment by vvo** [comment]
@vinhlh Using connectPagination along with https://github.com/avocode/react-shortcuts or https://github.com/chrisui/react-hotkeys I believe you should be able to achieve what you want.

Then should our own widgets handle that for you and expose that to the user, that's a tricky question. @Shipow do you think our pagination widget should implement keyboard shortcuts abilities by default?

We did implement shortcuts for the searchbox for instance because multiple websites had defined default shortcuts to access searchboxes. As for pagination do you know any very common website that had implemented it?

Maybe first we could do a guide if this is something people are looking for.

**Comment by vinhlh** [comment]
@vvo thanks 👍  I believe that's all I need.
We should not put this feature into the `library`, `connectPagination` is too good enough.
And keyboard navigation is not really common, it's only available on some kinds of web `application`.
