### ISSUE TITLE
Hierarchical widget issue

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#191]
There is a issue when you click on a non root level refinement

Steps to reproduce:
- on instantsearch.js branch of Magento, just click on a sub level

**Comment by vvo** [comment]
Are you able to reproduce it on the instantsearch.js `npm run dev` example?

**Comment by vvo** [comment]
Ok that's only because you are using an `<input type="checkbox" />` as a hierarchical facet template. Thus that's a case we did not planned, if you use a regular `<a href='#'` it will be ok.

And that's what you should use because it's not very good to use an `<input>` and then force the rendering to looks like it's not an input.

Use a different template for the (hierarchical) menu, that's no big deal and it should be easier to understand for the users in fact.

**Comment by vvo** [comment]
Maybe explain why you want to have an `<input>` (beside trying to have only one template for facets).

Also the default template should be enough maybe try it.

**Comment by maxiloc** [comment]
Yes the main reason is having one template (and one set of css rules).
But even if we forget about this reason, I do not see why you could not have inputs for hierarchical. For me the content of the template should not change the overall behavior

**Comment by vvo** [comment]
Labels and checkboxes have a very specific behavior on clicks so we do not handle them when multiple level deep.

There is no point in using checkboxes for the hierarchical menu. In a menu you NEED links so that you can cooy paste the href and ctrl click to open in a new tab.

It will in the end look weird to you users to have a hidden checkbox just to avoid having a different template.

You have two different UI element, you need a different template here.

**Comment by vvo** [comment]
You can have two templates and common css rules thats no big deal, do not try to DRY too much on templates bc youll end up with weird constructs in the code and css

**Comment by maxiloc** [comment]
Ok makes sense. Will do that

**Comment by maxiloc** [comment]
Tried it, I got the same issue with link or without it does not work. I updated the instantsearch.js branch on the magento repo

**Comment by vvo** [comment]
Will try again

**Comment by vvo** [comment]
So the issue is that you maybe not tried using `<a href=#` because it works with it. I will have to check why it's not working with simple `<div>` because that's an issue.

**Comment by maxiloc** [comment]
It was not working for me when I did it with a wrapping <a href="#"></a> arround .sub_facet

**Comment by vvo** [comment]
Ok fixed (will release soon so that you can continue working), next time you should try to reproduce the issue within the instantsearch.js repo/dev example in a branch so that it's a lot easier. Well, we fixed it now :)

**Comment by maxiloc** [comment]
Ok cool
