### ISSUE TITLE
Make search function provide a better API

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#1924]
This is a feature for instantsearch.js V2 -- breaking change

Right now, we have a function that can be given to the instantsearch factory called searchFunction. This function is given a helper that can't be modified, only the search function can be really used. Instead we could only provide a single function `search` as a parameter.

## API proposal

```js
instantsearch({
  searchFunction: (search, searchParameters) => {
     search(searchParameters.setQuery(''));
  };
});
```

In this example, the function will prevent the query to be set.

**Comment by vvo** [comment]
Yes to this. This is a breaking change it seems?

**Comment by bobylito** [comment]
Yes it is!

**Comment by timkelty** [comment]
I've found myself confused on when I need to use `instantsearch.helper` and when I need to use the shallow-clone of it in `searchFunction`.

Because the `searchFunction` param is just a shallow clone with `.search()`, if I need any other methods (e.g. `setQueryParameter`), I need to use `instantsearch.helper`. However, once I actually `.search`, I need to use the helper from the `searchFunction` param.

Here's an example. I want to prevent initial searching, listen for a map event and `setQueryParameter`, and then search. To do this, I have to juggle between both of the helpers, which seems icky and confusing.

```
var myMap = Leaflet.map('my-map');
var clonedHelper;

var instantSearch = new InstantSearch({
  searchFunction: (helper) => {
    clonedHelper = helper;
  }
});

map.on('moveend', (event) => {
  instantSearch.helper.setQueryParameter('insideBoundingBox', '...');
  clonedHelper.search();

  // Doesn't work
  // instantSearch.helper.search();
});
```

**Comment by bobylito** [comment]
Hi @timkelty Actually we failed you here, we are not providing enough resources for the kind of use case you have. The correct way (as instantsearch.js is designed) is to create a custom widget for you map component:

```js
var mapWidget = {
  init: function({helper}) {
    this.map = Leaflet.map('my-map');
    map.on('moveend', (event) => {
      helper.setQueryParameter('insideBoundingBox', '...').search();
    });
  }
}
```

I hope this will help you.

**Comment by timkelty** [comment]
@bobylito ah, thanks! That helps a lot.

Sorry to hijack the issue!

**Comment by bobylito** [comment]
@timkelty Power to the user!! We want to hear from you :D

**Comment by bobylito** [comment]
We've implemented the latest proposal in the latest beta of instantsearch.js v2. It works fine except that now it poses problem for custom widget that want to bind on the help lifecycle as well. This is because of the behavior of an event emitter behavior as a prototype (with the use of immutable objects which don't update their values in place). see #2176
