### ISSUE TITLE
The currentRefinedValues widget doesn't show multi level values for hierarchicalMenu refinements

### ISSUE THREAD

**Issue by seafoox** [algolia/instantsearch.js#2016]
In the current implementation of the currentRefinedValues widget, when a sub level in a hierarchicalMenu is selected, only the deeper level is available & available in the currentRefinedValues state. 

![image](https://cloud.githubusercontent.com/assets/1101220/23456207/c2783eaa-fe72-11e6-8b05-19780e295ade.png)

```js
{
  type: "hierarchical",
  attributeName: "hierarchicalCategories.lvl0",
  name: "PlayStation 4",
  count: 7,
  cssClasses: Object
}
```

Would be useful to have the full path, as it's exposed in the [JS helper via the getHierarchicalFacetBreadcrumb method](https://github.com/algolia/algoliasearch-helper-js#asking-for-the-current-breadcrumb)

**Comment by bobylito** [comment]
Hey @seafoox thanks for this issue, that's indeed a very interesting remark. That could definitely be very useful.

**Comment by Haroenv** [comment]
This is fixed right now by showing only the value (in v2)

<img width="297" alt="screen shot 2018-01-11 at 16 16 14" src="https://user-images.githubusercontent.com/6270048/34833066-d3dd85e0-f6ee-11e7-8d09-60fda5095042.png">

**Comment by timmetj** [comment]
I'm not sure if this is the solution? I'm facing the same issue here.
You would expect to see:
- All menu levels in the refinement ("Digital Camera's" and "Digital SLR Camera's") When clicking on digital SLR camera's the parent selection still must be selected.
OR
- when you only show the deepest menu, and click on it, go back to the parent menu, and not to the root.

On both options you still have to clear the current menu, and not the whole menu. So going back to the parent item.

**Comment by samouss** [comment]
In the next version of InstantSearch.js (the `v3` currently in beta) I think we have the expected behaviour. Here is [an example](https://v3--instantsearchjs.netlify.com/stories/?selectedStory=CurrentRefinements.with%20hierarchicalMenu), don't hesitate to provide us feedback on the baheviour and / or on the beta version!

**Comment by timmetj** [comment]
Hmm not quite. It still removes the whole menu selection. It should bring you to the parent level (Camera's & Camcorders), same as a breadcrumb would do.

**Comment by samouss** [comment]
For the moment this is the behaviour we have inside all the InstantSearch flavour (JS, React, Vue, Angular). To support the proposed solution it does not require a lot of work but it would change the default behaviour and it won't be backward compatible. I don't think it bring value to add an option to support this feature since it can be implemented with the connector API (or even with a [`breadcrumb`](https://community.algolia.com/instantsearch.js/v2/widgets/breadcrumb.html)). So it's either we keep what we have now or we change the implementation for your suggestion. I've open [an issue](https://github.com/algolia/instantsearch.js/issues/3346) to discuss that with the team.

**Comment by timmetj** [comment]
How to achieve this with the connectCurrentRefinedValues then? Since we use this already, but i can only find the lvl.0 in the refinements. using [js example](https://github.com/algolia/instantsearch.js/blob/develop/dev/app/jquery/widgets/currentRefinedValues.js)

And breadcrumb is another UX item ofcourse, which we already use, but aint the functionallity of a clear filter.

Also the hierachical menu itself has a strange way of (de)selecting a parent item. Using v3 [example](https://v3--instantsearchjs.netlify.com/stories/?selectedStory=CurrentRefinements.with%20hierarchicalMenu) You/I would also expect here when you click on "Camera's & Camcorders" it would go to that menu-item, now it also goes to the root, so it doesn't functional as a menu but as a checkbox on/off

**Comment by samouss** [comment]
With the version 2 I don't you have access to it. But with the v3 you have the complete path. You can split the current refinement with the `separator` to build each level of the hierarchy. For the last question I'm not sure to understand. In [this example ](https://v3--instantsearchjs.netlify.com/stories/?selectedStory=HierarchicalMenu.default) when we select "Cell Phones > Cell Phone Accessories > Car Chargers" then click on "Cell Phone Accessories" it does go on that level. Is not what you would expect?

**Comment by samouss** [comment]
Ah I got it, thanks for the example. I've created [an issue](https://github.com/algolia/instantsearch.js/issues/3349) for this too.

**Comment by timmetj** [comment]
Thank you, looking forward to it
