### ISSUE TITLE
[range slider] When min === max, the render is null

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2037]
Bug.

From what I've [read in the code](https://github.com/algolia/instantsearch.js/blob/develop/src/components/Slider/Slider.js#L26-L30), when passing min, max with min===max, it breaks the underlying implementation, that's why we're displaying nothing.

However, the widget implements a `autoHideContainer` with this exact predicate. This means that even if we set autoHideContainer to `false`, nothing will ever be displayed.

## Ideas for a fix

 - Since it breaks the underlying implementation, we could display a message?
 - We could provide refine with slightly different values so that it doesn't break?

## Reproducing the bug

http://codepen.io/team/algolia/pen/42391e8ff756274bc148f915823177bc/

 - type `bless` in the query -> range slider is displayed
 - type `blessin` in the query -> no more range sliders even there is `autoHideContainer:false` in the config

**Comment by iam4x** [comment]
From the comment in the code we can now understand why the `react-nouislider` component is not rendered when min === max.

```js
// There's no need to try to render the Slider, it will not be usable
// and will throw
```

And from @vvo comment on issue https://github.com/algolia/react-nouislider/issues/34#issuecomment-283062247 is recommending to use another library. I think we should the same and re-enable the render of the Slider when min === max but with a distinct "disabled" state.

I'm good to try to implement the use of https://github.com/airbnb/rheostat instead of `react-nouislider`, what do you think?

**Comment by bobylito** [comment]
Sounds good to me! We should be careful that we are able to provide the same css classes to avoid a breaking change.

**Comment by iam4x** [comment]
Good point, finally will do a POC with a fake disabled slider [here](https://github.com/algolia/instantsearch.js/blob/develop/src/components/Slider/Slider.js#L26-L30) using the same CSS instead of rendering nothing 👍

**Comment by Haroenv** [comment]
Closing via #2041 (GitHub didn't automatically since v2 is the base branch, and not develop)
