### ISSUE TITLE
Search multiple indices with combined results in one hits area

### ISSUE THREAD

**Issue by Giovanni-Mattucci** [algolia/instantsearch.js#2129]
Through Algolia's API I can see that [it is possible to query multiple indices](https://www.algolia.com/doc/api-client/javascript/search/#search-multiple-indices).
But is it possible to have two sets of results ranked against each other?

The main use case is, you have two indexes of data with different properties, but you want to give the user the ability to see results from both **and ranked against each other** (this is key). 

You could add multiple indexes when configuring instant search:
```
instantsearch({
  appId: config.appId,
  apiKey: config.apiKey,
  indexNames: ['index1','index2'] 
});
```
Now each query would apply a search to both, and return a combined result that ranks them against each other.

I'm sure there are complications in being able to rank two different structures against each other, but often you have very different data sets and want to embed along with them some other kind of data.

One example would be, you have an index of web pages, and you have an index of company locations.
You want a user to be able to search the web pages for specific content, but if their search matches company locations, you want to highlight those in order of relevance to other web page results to the user.

Could something like this be done by creating a custom instantsearch widget where you manually combined two sets of results in some fashion?

**Comment by Giovanni-Mattucci** [comment]
I found this discussion: ["Compare ranking of Algolia query across multiple indices"](http://stackoverflow.com/questions/32615483/compare-ranking-of-algolia-query-across-multiple-indices)
Perhaps what I am looking for is better done by combining data into 1 index, and then querying that index.

**Comment by bobylito** [comment]
Hi @Giovanni-Mattucci you can't have records from different indices and aggregate them in a single list with Algolia.

**Comment by lud-wj** [comment]
Hi @bobylito , what did you end up doing? Our use case is that we have two indexes from the same data but we do not want to match the query on the same fields. Does that ring a bell?

**Comment by lud-wj** [comment]
Hi @Giovanni-Mattucci  , what did you end up doing? Our use case is that we have two indexes from the same data but we do not want to match the query on the same fields. Does that ring a bell?

**Comment by lud-wj** [comment]
Thank you @Haroenv , we are indeed trying to find a solution to mix the indices a single search request, because frontend solutions will not work for us (mostly because we need to paginate over 1000 results).

Infortunately we need to run a query over different fields, so this looks like a dead end.

**Comment by Haroenv** [comment]
Does it _need_ to be different fields? can you not alias both to a single set of consistent fields?

**Comment by lud-wj** [comment]
I am not sure I follow you. We need to search "foo" in fields A,B,C and "bar" in fields B,C,D. We must _not_ match "foo" in field D and "bar" in field A.

How I understand things is that if you want to be able to have ranked results and correct pagination server side:
*  you must use only one request
* to match those fields you need to use the `query` (those are not facets)
* a single query means a single set of fields to match from.

Am I missing something here?

**Comment by Haroenv** [comment]
Surely you can't search for foo and bar in the same interface? the query must be equal if you're going to do a single UI.

However what you can do is map the fields to be the same across all record types:

```
// before
{ a: 'something' }, { b: 'something' }
// after
{ a: 'something', combined: 'something' }, { b: 'something', combined: 'something' }
```

You can still use a or b conditionally to display record-specific information, as long as the actual searchable attributes are equal, you can rank them.

In a lot of cases you can even use the first records, and simply add both a and b in the searchable attributes.

If I'm missing something, please give real examples of records that should and shouldn't match different queries.

**Comment by lud-wj** [comment]
(Thank you for taking the time!)

The two indexes have the same data actually, they just happen to have different
`searchable_attributes` (not sure why it has been made this way because we can
override that parameter on resquest)

And you will find records like this:

```json
{
  "favorite_foods": ["apples","oranges","bread"],
  "description": "I love to foo and also bar"
}
{
  "favorite_foods": ["aples","ORANGES!!"],
  "description": "Just foo for me"
}
```

And a user query = `?keywords=foo bar&foods=apples oranges`. So we were doing two requests, one to match the `keywords` on all fields, and the `foods` on `favorite_foods` only. (Made up example)

**Comment by Haroenv** [comment]
In the UI, do you have two separate search boxes for this then? or are you relying only on the URL and there's no ui to set these queries?

For me favorite_foods seems more like a use case for facets than for search. I wonder if you can normalise the values first so they don't have misspellings, before indexing. Then you can use `filters` or `facetFilters` for the `favorite_foods` attribute, and `query` for the full text search.

Are the favorite foods coming from user input? 

Alternatively you could also add a rule on the "matches facet" for favorite foods and then apply that facet, remove the word from the query, if there's only one input: https://www.algolia.com/doc/guides/managing-results/rules/detecting-intent/

In search there's only one query, because there's only one actual search happening. This is because if you don't share a query, you can't compare the sets of results, and therefore also wouldn't be able to show the most relevant results.

Hope this helps, but it may be interesting to contact your solutions engineer for more a more in-depth conversation.

**Comment by lud-wj** [comment]
Yeah sorry the example is not great but favorite food is indeed user submitted text. 

We cannot use facets in there. We have two search boxes in the UI yes, that lead to two query string properties, but only one resultset in the UI, we cannot split the results in two panels for instance.

We could normalize those foods. We discussed it and found another problem but I can't remember it. It's still a possible solution though, but it is not what we want.

We are also discussing using weighted results instead, searching "foo" in favorite foods but with much less score impact.

And yes, I guess the Algolia team could help us on that!
