### ISSUE TITLE
New website review

### ISSUE THREAD

**Issue by redox** [algolia/instantsearch.js#2136]
Awesome job on the new documentation & website 👍  I really like the new getting started & guides 💯 

A few minor issues I've spotted:

 - [x] Would love to have a sticky left menu
 - [x] Wondering whether we should push ES6 syntax or not in examples?
 - [x] the DocSearch implementation is still referencing the Android index :)
 - [x] Homepage's hero is not responsive
 - [x] On the `/instantsearch.html` page, the markdown is broken:

![screen shot 2017-05-10 at 08 51 38](https://cloud.githubusercontent.com/assets/29529/25886472/ffb8a9b8-355d-11e7-923c-8049539c9157.png)

**Comment by Haroenv** [comment]
seems like that paragraph isn't rendered in markdown https://github.com/algolia/instantsearch.js/blob/feat/instantsearch.js/v2/docgen/layouts/instantsearch.pug#L33-L36

for the fourth checkmark, see #2134

**Comment by iam4x** [comment]
* I agree for the sidebar fixed I've pushed a commit (https://github.com/algolia/instantsearch.js/commit/5244bda2b8eb97465df2543648aadf686760edff)
* Pushed a fix for the homepage hero on mobile (https://github.com/algolia/instantsearch.js/commit/b9d1cf97f80e2a2085fdc54c8c37eadc1004ce18)
* Also little fix for instantsearch.html markup (https://github.com/algolia/instantsearch.js/commit/d36b42ce536bcd93546ecafd6a56ec80e68ef223)

About pushing ES6 we thought that advanced users who already know ES6 syntax will transform them by themselves. Since we do not target only this kind of users it might be easier for the more junior in JS. What do you think @redox @bobylito ?

**Comment by Haroenv** [comment]
It's all supported in evergreen browsers now though, and most courses that aren't w3schools already start with it AFAIK

**Comment by Haroenv** [comment]
the major difference would be arrow functions and const instead of var, right?

**Comment by iam4x** [comment]
Yes @Haroenv

**Comment by iam4x** [comment]
Reverted the fixed menu, there is no "simple" solution to make it fixed and works everywhere.

![2017-05-10 14 01 29](https://cloud.githubusercontent.com/assets/893837/25898565/f23ce4dc-358c-11e7-82c3-21ac1a15360d.gif)

**Comment by bobylito** [comment]
About the ES6 syntax, I was wondering how widespread it is and it seems that as @Haroenv said ES6 is implemented is all the latest versions of browsers. This means that since we have a developer  audience and we're gonna use a limited set of features, it makes sense to update the examples to ES6.

**Comment by bobylito** [comment]
And let's push the sticky menu for when we'll do the implementation of the design with the design team :)

**Comment by Haroenv** [comment]
As reference, `const` is since IE11 ([caniuse](http://caniuse.com/#feat=const)) and `=>` is since Edge/Safari 10 ([caniuse](http://caniuse.com/#feat=arrow-functions))

**Comment by bobylito** [comment]
> But I assume that people who want to support lower will test lower and know that it's not yet supported?

My thoughts exactly!
