### ISSUE TITLE
Increase limit of pagination above 100 pages of results, allow more than 1000 returned results.

### ISSUE THREAD

**Issue by Giovanni-Mattucci** [algolia/instantsearch.js#2177]
So currently the pagination widget limits the max number of pages you can have at 100, and I guess this is because the limit of returned results using instantsearch.js is 1000 records.

I would expect this to allow you to paginate through all the results in the index, or at least have this configurable.

Perhaps a solution is after getting the first 1000, that then a query is done for the next 1000?

**Comment by Haroenv** [comment]
It’s possible if you set `paginationLimitedTo` to a higher value in each index.

However, it’s not ideal since it has a performance, and usually not necessary, since users rarely go beyond the first pages. 

> We recommend keeping the default value to guarantee excellent performance. Increasing the pagination limit will have a direct impact on the performance of search queries. A too high value will also make it very easy for anyone to retrieve (“scrape”) your entire dataset.

see https://www.algolia.com/doc/api-client/javascript/parameters/paginationLimitedTo/

Have a great day!
