### ISSUE TITLE
Get a list with all hits at once

### ISSUE THREAD

**Issue by pierre-vr** [algolia/instantsearch.js#2251]
Hi everyone!

I am struggling with InstantSearch to get a list with all the hits (and not only the x most relevant).

Is there an easy way (or even a hard way) to get a simple list of all the hits?

Thanks !

**Comment by Haroenv** [comment]
Hey Pierre, did you check out the [hits](https://community.algolia.com/instantsearch.js/v2/widgets/hits.html) widget? 

It's also mentioned in the [getting started](https://community.algolia.com/instantsearch.js/v2/getting-started.html#display-results)

**Comment by pierre-vr** [comment]
Hi Haroenv!
Sure I did. But I only manage to display the 10 or 20 first hits, I would like to display them all.

I have notice also the infinitHits widget but this isn't what I am looking for as you have to click on "Show more" to get more.

**Comment by Haroenv** [comment]
Algolia is focused on search, that means that people should search for a result, and then refine, if people are searching for something they don't find on the first few pages, they will usually refine differently. 

Since changing a page in InstantSearch doesn't require a full page request, changing a page here is almost negligible qua user impact.

If you want a bit more than 20 hits per page, you can change the [hitsPerPage](https://www.algolia.com/doc/api-reference/api-parameters/hitsPerPage/) parameter, and if that still isn't enough, you can take a look at [paginationLimitedTo](https://www.algolia.com/doc/guides/searching/pagination/#overriding-the-default-limits).

If you want to get all the results of an index for some specific use case, you can use [browse](https://www.algolia.com/doc/api-client/php/advanced/#backup--export-an-index)
