### ISSUE TITLE
New widget: RangeInput

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2317]
In react-instantsearch, there is a [RangeInput widget](https://community.algolia.com/react-instantsearch/widgets/RangeInput.html) to be able to set a range with two inputs. We can implement with connectRangeSlider. In the process, we should probably alias connectRangeSlider to connectRange and deprecate connectRangeSlider.

**Comment by samouss** [comment]
I looked into the existing components and I found that [PriceRanges](https://community.algolia.com/instantsearch.js/v2/widgets/priceRanges.html) is pretty much the same as the [RangeInput](https://community.algolia.com/react-instantsearch/widgets/RangeInput.html). Basically the `PriceRanges` is a composition of a `RangeInput` with a list of ranges.

So instead of using the `connectRangeSlider` as connector, we might use the `connectPriceRanges` to implement the `RangeInput` widget and reuse the `RangeInput` component inside `PriceRanges`. With this we can remove the logic for the inputs in `PriceRanges` and handle only the refinement on ranges.

As a side note, we can also rename the `PriceRanges` widget (& connector) for a more generic name like `RangeInputList` (any ideas?) because it's not strictly limited to a range of prices. We can imagine it with sizes, weights...

What do you think about it?

**Comment by bobylito** [comment]
Nice comments @samouss 👍 I have a few questions remarks:
 - ok if the the connectPriceRanges makes more let's go for it
 - do you suggest to remove the inputs in the price ranges?
 - ok for changing the name. However I would still alias the new names to the old so that we don't introduce a breaking change here, add a deprecation notice and drop the deprecated names when we move to a new major version.

**Comment by samouss** [comment]
@bobylito Yes, I suggest to remove the inputs and replace them with the `RangeInput` component built for the `RangeInput` widget (without changing the behavior of `PriceRanges`).

**Comment by bobylito** [comment]
Ok then as long as we don't break the public API that's perfectly fine! 👍

**Comment by iam4x** [comment]
Thank you for the proposition @samouss I was having the same thoughts at some point and it goes into the direction to have the same widgets name on every instantsearch.js library 👍
