### ISSUE TITLE
Need some help. Laravel+Algolia Star of Items - Please guide me!

### ISSUE THREAD

**Issue by sadamameer** [algolia/instantsearch.js#2324]
Hi, 

I am using Algolia in my web system and I really like this service. The only thing on which I am stuck is I want to show star rating of items, you can see picture attached below for more clarification.

I don't want rating widget. I have an attribute called rating that has float values like 3.54 etc. I am using Laravel 5.4

![untitled](https://user-images.githubusercontent.com/10099463/30240401-b6463e9a-9524-11e7-80a8-8ebb8f983f36.png)

**Comment by Haroenv** [comment]
Do you want to just show the stars, or should it also do something when you click on it? 

To just show it you can use [the template](https://community.algolia.com/instantsearch.js/v2/widgets/hits.html#struct-HitsTemplates) and loop over the stars until you have the right amount.

**Comment by sadamameer** [comment]
@Haroenv I just want to show stars of each item. I have an attribute names rating which has float value. How can I show stars with that float value of each item.? can you please share some code with me. I have seen that documentation but I did not get anything ng from there that I need. In "hits" template, I want to show the rating of each item with stars like I posted the picture above.

Thanks for reply 👍 waiting for next reply ....

**Comment by bobylito** [comment]
Hi @sadamameer, in order to do that you need to implement two things. One is a [transformData](https://community.algolia.com/instantsearch.js/v2/widgets-common-api.html#transformdata), that will let you process your floats into elements that can be used in the the template. You can find an example for the [transformData of a star rating here](https://github.com/algolia/instantsearch.js/blob/e78de702ed53798431493df6e966a53d749930d7/docgen/src/examples/media/search.js#L44-L50). The other is the template. You can find the star rating template a [little above the transform](https://github.com/algolia/instantsearch.js/blob/e78de702ed53798431493df6e966a53d749930d7/docgen/src/examples/media/search.js#L28) data.

Just as a side note, the issues in this project are for bug reports or feature proposal. Only opening issues for bugs or features really helps us maintain a good quality on the project.

If you're looking for support, we suggest that you go through the [Algolia community forum](https://discourse.algolia.com/) or [stack overflow](https://stackoverflow.com/tags/instantsearch.js/). We try to be reactive on those two platforms and  Thanks for using InstantSearch.js and Algolia ❤️

**Comment by sadamameer** [comment]
@alexandremeunier Thanks, alot problem is resolved. you are awesome 👍

**Comment by Haroenv** [comment]
You're also awesome 😎 @sadamameer
