### ISSUE TITLE
Hierarchical Facet Refinements level is always 0

### ISSUE THREAD

**Issue by MatthewRuddy** [algolia/instantsearch.js#2436]
**What is the current behavior?**
I'm using `hierarchicalMenu` widget with attributes `['categories_en.lvl0', 'categories_en.lvl1', 'categories_en.lvl2', 'categories_en.lvl3']`.

When I chose a category of level 2, it seems the refinement value is set with key `categories_en.lvl0` instead of `categories_en.lvl2`.

<img width="603" alt="screen shot 2017-10-03 at 12 35 34" src="https://user-images.githubusercontent.com/2593287/31123383-97da2504-a837-11e7-95a6-918dd5cb18f7.png">

This means that the level 2 category is actually considered level 0.

**What is the expected behavior?**
I would expect the refinement to be `categories_en.lvl2`, thus allowing us to still refine `categories_en.lvl1` or `categories.lvl0`. Particularly, locking them down via `searchFunction` on initialisation on the page for a specific category.

**What browsers are impacted? Which versions?**
All browsers. Using version instantsearch.js 2.1.6 currently.

**What is the proposed solution?**
Ensure refinement level matches that of what is selected.

**Comment by bobylito** [comment]
Hi @MatthewRuddy thanks for opening this issues.

The data organization is misleading here. In the Helper (the library that handles the state of the search inside InstantSearch.js), there is an option for naming a group of attributes as a "hierarchical facet". Since this option is technical in instantsearch.js, we didn't choose to expose it. Instead we use the first attribute as the name of the hierarchical facet.

Your state is perfectly normal.

Hope that answers your question.
