### ISSUE TITLE
API Proposal: Theming draft

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#247]
For a first version here's what theming could look like:
- we have BEM classes in React Component (that's already mostly the case)
- we have inline BEM classes in the default templates (without being able to override them, I think this is not necessary). For example `<span count="ais-refinementList.."></span>`.
- we create a default.css in themes/ that will do the minimum styling so that:
  - it uses the BEM classes to style
  - the default theme is usable
  - it contains all the classes of the project, even if they are empty, so that a user can quickly copy paste it and tune it or understand it
  - the default theme does no have too strong defaults, to be able to easily override them from a user.css
- modify jsdelivr to be able to deploy css files
- remove every css files from the instantsearch.js javascript, we will load them separately as <link> for now

Let's not go right now into API needs to be able to override all the default templates (use case: bootstrap compliant markup + theme).

**Comment by redox** [comment]
:+1:

**Comment by pixelastic** [comment]
- From a technical point of view, I thing BEM classes should be defined in the widget, and then passed to the React component. This will let us share some components (like `refinementList`) but still allow them to have different classes (`ais-toggle` and `ais-menu` instead of all having `ais-refinement-list).

- If we remove the ability to override classes of default templates we lose the ability to do a Bootstrap-compliant theme easily (one can still override the whole template). I have no problem dropping that for the v1, but we need to be clear on that.

- Ok for the `default.css`. We'll still need to see what will go inside and will go in the bigger themes.

**Comment by vvo** [comment]
> From a technical point of view, I thing BEM classes should be defined in the widget, and then passed to the React component. This will let us share some components (like refinementList) but still allow them to have different classes (ais-toggle and ais-menu instead of all having `ais-refinement-list).

Let's go to be able to configure the whole BEM classes, we will see if it's well used or not later on, no big deal. We just need to make sure that we document the widgets options with some priorization. From most used features to least.

**Comment by pixelastic** [comment]
I think we're good on that one.
