### ISSUE TITLE
SFFV in refinementList has invalid html for highlighting

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#2474]
see also https://discourse.algolia.com/t/searfforfacetvalue-highlight-bug/3198

**Do you want to request a *feature* or report a *bug*?**

bug 😢 

**Bug: What is the current behavior?**

The highlightPreTag is set to the `__ais-highlight__`, like the post tag when the hits widget has the `escapeHits` flag set to `true`. It's not set back to the original tag used by highlighting, or one configurable in the widget.

**Bug: What is the expected behavior?**

nobody should notice we are using a different tag against XSS

**Bug: What browsers are impacted? Which versions?**

all

**Bug: What is the proposed solution?**

replace the preTag and postTag by default with em, split up the text in pieces and insert text before and after

Maybe an option to insert html, but only when someone asks for it

**What is the version you are using? Always use the latest one before opening a bug issue.**

I think latest?

**Comment by iam4x** [comment]
Nice catch 👍

**Comment by bobylito** [comment]
Indeed this was already open. Thanks for closing the other one @Haroenv. As per the solution the problem is that this is related to an option that is in another widget (hits). One quick fix is to be able to identify that there was a post and pre tag that were set, and convert back to `<em>`. The problem is that it might be custom settings, and the user would be surprised to `<em>` instead of it own custom config. Another approach is to have a new independant setting `escapeFacetHighlight` but then it requires to change the `searchForFacetValues` method in the helper, because currently it doesn't support passing custom settings. I think the latter is the best option.

**Comment by bobylito** [comment]
As far as I understand, this is done. Please re-open if something was missed :) (or even better create a new issue :))
