### ISSUE TITLE
urlSync combined with specific searchFunction does not updates on first letter

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#2523]
**Do you want to request a *feature* or report a *bug*?**

bug

Test case: https://jsfiddle.net/8bqdcrg3/8/, this console.log the location.href continuously.

**Bug: What is the current behavior?**

When using this searchFunction:

```
{
  searchFunction: function(helper) {
    var query = helper.state.query;
    // with this code the url is not updated on first letter
    // while the search is being done
    if (query === '') {
	    return;
    }
    helper.search();
  },
}
```

The urlSync will not be triggered for the first typed letter, but only at the second one.

**Bug: What is the expected behavior?**

urlSync must be triggered for the first letter

**Bug: What browsers are impacted? Which versions?**

all

**Bug: What is the proposed solution?**

I don't know

**What is the version you are using? Always use the latest one before opening a bug issue.**

2/

**Comment by vvo** [comment]
This issue can be fixed easily by only adding:

```
    if (query === '') {
        helper.search(); // <-- still do a search when query is empty, fixes the urlSync on first letter
	    return;
    }
```
So in the end, the usecase being "hide hits when no query" and not "do not do any search when query is empty", we could mark this as fixed and answer the person..


WDYT?

**Comment by bobylito** [comment]
It's not very practical to see the URL update with jsFiddle. I move the example to surge: http://verdant-coat.surge.sh/

**Comment by bobylito** [comment]
> So in the end, the usecase being "hide hits when no query" and not "do not do any search when query is empty", we could mark this as fixed and answer the person..

Yes but since you qualified it as bug, I don't know :) For now, if it's an acceptable workaround (change the UI behaviour, not the InstantSearch.js behaviour), go for it.

However since I've checked [the InstantSearch.js code](https://github.com/algolia/instantsearch.js/blob/2ed948dcae94f0b6ca217a083acc8ad2e6337754/src/lib/url-sync.js#L136-L140), I have the feeling we might be able to do something. What happens is that we setup the mechanics to bind the search to the browser URL during the first rendering. The idea is that this way we prevent the first rendering to update the URL. The thing we want to avoid is an update to an empty query URL which will have at least `?q=`, which is weird because happened yet.

But there might be a way to fix that. The code [retrieves the state from the URL before the start](https://github.com/algolia/instantsearch.js/blob/develop/src/lib/url-sync.js#L117-L120) of InstantSearch.js lifecycle. This means that during the first rendering, we are able to figure out if the current state of the search is different from the initial parameters. If it's different then we should update the URL, otherwise we keep the same.

What do you think @vvo ?

**Comment by vvo** [comment]
> If it's different then we should update the URL, otherwise we keep the same.

That should work indeed!

**Comment by vvo** [comment]
(I answered the underlying helpscout ticket)
