### ISSUE TITLE
[refinementList] sortBy doesn't factor in transformData

### ISSUE THREAD

**Issue by razvanh** [algolia/instantsearch.js#2648]
When adding a transformData function to a refinement list, it is not factored in when sorting the refinements. The bug is reproduced here: https://jsfiddle.net/9ej3v2t6/

1. added a refinement list widget for genres.
2. added transformData function that changes the label of one of the genres from "Comedy" to "Humor"
3. added `sortBy:['name:asc']` and would expect the refinements to be sorted correctly but we get Action, **Humor**, Crime etc.

This problem can be circumvented by using a custom function for sortBy, something like this:

```
sortBy: function(a,b){
  const genres = {'Comedy':'Humor'};
  var nameA = a.name.toUpperCase(); // ignore upper and lowercase
  var nameB = b.name.toUpperCase(); // ignore upper and lowercase

  if (genres.hasOwnProperty(a.name)) nameA = genres[a.name].toUpperCase();
  if (genres.hasOwnProperty(b.name)) nameB = genres[b.name].toUpperCase();

  if (nameA < nameB) {
    return -1;
  }
  if (nameA > nameB) {
    return 1;
  }
 // names must be equal
 return 0;
}
```

**Comment by bobylito** [comment]
Hi @razvanh, indeed `sortBy` is applied before `transformData`. I'm not sure whether we should "fix" that because some might rely on this behaviour. I'll sync up with the team.

**Comment by francoischalifour** [comment]
This problem is not present anymore with [`transformItems`](https://www.algolia.com/doc/api-reference/widgets/refinement-list/js/#widget-param-transformitems), introduced in [2.10.0](https://github.com/algolia/instantsearch.js/blob/develop/CHANGELOG.md#2100-2018-08-08). This function is applied after `sortBy`.

You can read more on how to migrate to this API in [our InstantSearch.js v3 migration guide](https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/js/#transformdata-is-replaced-by-transformitems).
