### ISSUE TITLE
Multiple sortBySelector interfere with each other

### ISSUE THREAD

**Issue by hcarreras** [algolia/instantsearch.js#2747]
I want to sort my orders by multiple attributes. I've created replicas for my primary index:
![](https://cl.ly/2u451Z22460V/Image%202018-02-22%20at%202.14.59%20PM.png)

Then, on my js (coffeescript), I use instantsearch for adding multiple sortBySelectors:

```
  search.addWidget(
    instantsearch.widgets.sortBySelector
      container: '#sortBySelectorUserName'
      indices: [
        { name: 'Order_development', label: 'User name' },
        { name: 'order_user_name_asc', label: 'User name asc' },
        { name: 'order_user_name_desc', label: 'User name desc' }
      ],
      cssClasses:
        select: ['sort-by']
  )

  search.addWidget(
    instantsearch.widgets.sortBySelector
      container: '#sortBySelectorCustomerName'
      indices: [
        { name: 'Order_development', label: 'Customer name' },
        { name: 'order_customer_name_asc', label: 'Customer name asc' },
        { name: 'order_customer_name_desc', label: 'Customer name desc' }
      ],
      cssClasses:
        select: ['sort-by']
  )
```

Unfortunately, when I change one of the dropdowns, the other one gets affected as well:
![](https://cl.ly/0F2R3z3a1c1H/Screen%20Recording%202018-02-22%20at%2002.18%20PM.gif)

How can I keep the label name on the other dropdowns while sorting?
Perhaps I'm missing a key concept?

**Comment by bobylito** [comment]
The widget doesn't support multiple instance the way you're doing it because they are not aware of the others and the default behaviour. Maybe you can work around that by implementing a [custom widget](https://community.algolia.com/instantsearch.js/v2/guides/customization.html) using the [connectSortBySelector](https://community.algolia.com/instantsearch.js/v2/connectors/connectSortBySelector.html) [connector](https://community.algolia.com/instantsearch.js/v2/connectors.html)?

**Comment by bobylito** [comment]
I'll close this one for now. Thanks for your contribution @hcarreras Don't hesitate to open a new issue if you have other questions or if you want to report other shortcomings.
