### ISSUE TITLE
Possibility to toggle searchable attributes

### ISSUE THREAD

**Issue by stelem** [algolia/instantsearch.js#2875]
Hello,

i would like to ask you, if there is the possibility to toggle a searchable attribute via checkbox. 

E.g. the user searches for a special "keyword" but can't find it. So he checks the box for "fulltext search" and can find a keyword by any definition. 

The only solution i've found, was to index the keywords twice. Once with and without the "fulltext".

Thanks for your help.

**Comment by bobylito** [comment]
Hi @stelem unfortunately [searchableAttributes](https://www.algolia.com/doc/api-reference/api-parameters/searchableAttributes/) is a setting parameter. It can't be changed with search parameters.

On the Algolia side, one way is to rely on primary / secondary with different searchableAttributes.

And then switch the index on the fly. You can use the [sortBySelector](https://community.algolia.com/instantsearch.js/v2/widgets/sortBySelector.html) for that. But since you mentioned that you wanted a checkbox, then you probably want to have a look at the [connector](https://community.algolia.com/instantsearch.js/v2/connectors/connectSortBySelector.html).
