### ISSUE TITLE
slider: Simpler default CSS styles

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#289]
![image](https://cloud.githubusercontent.com/assets/283419/10601938/7f32efc2-7715-11e5-9e94-518e0e1c2515.png)

Current styles have strong opinion about colors/fonts/size. We should strip it down to the bare usable one in `default.css`.

**Comment by vvo** [comment]
Yes maybe just default to gray background, black font color and this should be enough?

**Comment by pixelastic** [comment]
The whole slider CSS code can be simplified I guess. It weight more than all the other widgets combined. But yes, no colors, no rounded borders at least.

**Comment by vvo** [comment]
Dunno if we need to spend some good time on this because it should still look good with very little styling. And no rounded borders I am not sure it still looks ok.

Our slider will always be the most styled widget because making it very generic and usable without too much styling is hard.

Defaulting to less shiny colors should be fine for now?

**Comment by pixelastic** [comment]
Yeah sure.

We just need to give this slider a little more love one day. This is still by far the most complex widget we have.

**Comment by vvo** [comment]
So what do we do here? Use less funny colors and black/gray only in default.css? If so create a new issue with clear goals:)

**Comment by redox** [comment]
I'll work on a default theme with @pixelastic; not yet sure what we're gonna do with the default styling of the slider but we'll create a new issue once it's more clear.
