### ISSUE TITLE
clearAllURL should be a function in connectCurrentRefinedValues

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2933]
clearAllURL is documented as a function but is actually a string. We will fix that in the doc so that we are consistent and do not break the current implementations (next minor). But for consistency with createUrl, it should be a function (next major).

Maybe we should update the name in this case, or think about changing the signature of the createURL function:
 - `createURL() => url with everything cleared`
 - `createURL(facet) => url with just facet cleared`

**Comment by francoischalifour** [comment]
The [`currentRefinements`](https://www.algolia.com/doc/api-reference/widgets/current-refinements/js/) widget in v3 doesn't make the distinction between clearing some and clearing all refinements. It's achieved with the `includedAttributes` and `excludedAttributes` options.

This issue is therefore not relevant anymore.
