### ISSUE TITLE
Provide a recipe for using turbolinks and the routing

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#2998]
**Is your feature request related to a problem? Please describe 🙏**
Turbolinks is a tech that simulates SPA on traditional websites. The URLSync was compatible, the routing is not.

**Describe the solution you'd like 🤔**
No clear solution for now but the routing should be compatible and we should document how to implement it.

**Additional context**
This is a follow up of https://github.com/algolia/instantsearch.js/issues/985

**Comment by Spone** [comment]
So I got it working in our project, but I have to leave the `turbolinks=true` param in the URL, or it doesn't work. I'd love to find a way to hide it and keep my routing clean :)

You can view the live implementation here: https://www.woom.fr/recherche/experiences?q=test&turbolinks=true

**Comment by bobylito** [comment]
Thanks a lot @Spone for the status update 👍 :)

**Comment by mayeco** [comment]
ping

**Comment by tdutreui** [comment]
hello :)
anything new around here ?

**Comment by Haroenv** [comment]
Nothing new; workaround is still: https://github.com/algolia/instantsearch.js/issues/985#issuecomment-388899593

```js
instantsearch({
  routing: {
    stateMapping: {
      stateToRoute(uiState) {
        return {
          turbolinks: true,
          ... uiState,
        };
      },
      routeToState({turbolinks, ...routeState}) {
        return routeState
      }
    }
  }
});
```

**Comment by Spone** [comment]
Hi there, I'm using the latest instantsearch.js on a new project and the Turbolinks support seems broken again... Any news on this?

**Comment by Haroenv** [comment]
(to fix this without workaround, we need to pass `turbolinks: true` in the "state" object of the `history.push`, right now this is the "route state", so that's why you need to manually add it. It might make sense to have an option for this in the `router`

**Comment by Spone** [comment]
Currently, when I use the recommended workaround, if I click on a link, I have to click the back button twice to get back to my original state. I'm not sure how to debug this...

**Comment by francoischalifour** [comment]
@Spone Can you please reproduce the behavior in this [InstantSearch.js sandbox](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js)?

**Comment by AlexandreSi** [comment]
Hi there,
I encountered the problem here:

1. Go to https://www.woom.fr/activites/Clermont-Ferrand/dans-les-airs
2. Click on "Parapente (...)"
3. See that results are updated
4. Hit back to return to previous page, see that we don't find the same page (actually, it's the page https://www.woom.fr/activites/Clermont-Ferrand that is rendered)
5. Hit forward button, see that we have the same results as step 4.

parseURL is never called.

Do you need a live reproduction of the bug in a sandbox?

Thank you

**Comment by Haroenv** [comment]
A standalone sandbox is the only efficient way where we can debug yes. What I think might be the case is the `turbolinks`

1. not sending updates when the url changes
2. gets Removed if `turbolinks` is removed from location.history

**Comment by AlexandreSi** [comment]
I am not sure how to reproduce it giving the fact that we install turbolinks via the ruby gem (our backend being rails). Maybe you can help on this?

**Comment by Spone** [comment]
> I am not sure how to reproduce it giving the fact that we install turbolinks via the ruby gem (our backend being rails). Maybe you can help on this?

You can install it using the NPM package: https://www.npmjs.com/package/turbolinks

**Comment by AlexandreSi** [comment]
Hi @Spone,
Thanks for the tip, I am just not sure that installing turbolinks a different way will reproduce the bug, I will try and see!
Thanks

**Comment by AlexandreSi** [comment]
Hi,

Here is a sandbox that should expose the problem: https://codesandbox.io/s/algolia-turbolinks-bad-behaviour-b5ed6?file=/src/app.js

The thing is that I didn't add turbolinks and I don't understand why parseURL is not called at each click on back or forward buttons, as described by your documentation.

Thank you again

**Comment by Haroenv** [comment]
Since it's unrelated to turbolinks, could you open this in a new issue please? I don't know for sure yet what the cause is, but I feel like it might be related to the URL not being different to before

**Comment by marckohlbrugge** [comment]
> Nothing new; workaround is still: [#985 (comment)](https://github.com/algolia/instantsearch.js/issues/985#issuecomment-388899593)
> 
> ```js
> instantsearch({
>   routing: {
>     stateMapping: {
>       stateToRoute(uiState) {
>         return {
>           turbolinks: true,
>           ... uiState,
>         };
>       },
>       routeToState({turbolinks, ...routeState}) {
>         return routeState
>       }
>     }
>   }
> });
> ```

Is this still the recommended workaround with the latest instantsearch and turbo(links) versions? Unfortunately it doesn't seem to have any effect for me (apart from adding `turbolinks=true` to the generated URL).

**Comment by Haroenv** [comment]
the state "turbolinks: true" still gets saved in the history state since it saves the whole route state:

https://github.com/algolia/instantsearch.js/blob/3648a3cdc561cca3d92c67f7c5121ed16d00c722/src/lib/routers/history.ts#L132

Alternatively you can change that line in a custom router to no longer save the InstantSearch state on history state,  but then you'll need to make sure you also don't read from event.state in onUpdate: 

https://github.com/algolia/instantsearch.js/blob/3648a3cdc561cca3d92c67f7c5121ed16d00c722/src/lib/routers/history.ts#L148

Hope that helps @marckohlbrugge, but otherwise it'll be best if there's a reproducible example with turbolinks + InstantSearch so we can investigate what's going wrong

**Comment by marckohlbrugge** [comment]
Thanks @Haroenv. I'll give it another try. Building a reproducible example is a bit tricky as both instantsearch and turbo links are quite hard to set up as standalone scripts. But I'll see what I can do if I still can't get it to work with your suggestions above.

**Comment by Haroenv** [comment]
In general I feel like it's usually better not to use turbolinks on the InstantSearch pages, as they will both conflict. It's best to set up an exclusion for any InstantSearch-controlled page. If there's anything else wrong after both scripts are no longer running on the same page, please create a new issue with reproduction :)

**Comment by Spone** [comment]
Here is the working solution in 2024, with current versions of InstantSearch.js 4 & Turbo 8:

```js
instantsearch({
  routing: {
    router: history({
      cleanUrlOnDispose: false,
      push: (url) => {
        window.history.pushState({}, null, url);
        Turbo.navigator.history.push(url);
      },
    }),
  },
})
```

[Source](https://discuss.hotwired.dev/t/back-button-not-working/3012/2)

**Comment by drale2k** [comment]
@Spone Thanks that worked mostly for me but i had to use `replace` instead of `push` `Turbo.navigator.history.replace(url);`

With using `push`, i could go back with the back button when leaving the search page but after that, every back button click would not do anything until i reach the last item in the history on the search page (initial state when loading the search page). 

With `replace` i can traverse back properly and routing works as intended.

**Comment by indykoning** [comment]
> With using push, i could go back with the back button when leaving the search page but after that, every back button click would not do anything until i reach the last item in the history on the search page (initial state when loading the search page).

This stems from `window.history.pushState({}, null, url);` and `Turbo.navigator.history.push(url);` meaning essentially the same thing.

See: https://github.com/hotwired/turbo/blob/3138f17574c27127c78697986ab1ac95dcca4d70/src/core/drive/history.js#L33
and: https://github.com/hotwired/turbo/blob/3138f17574c27127c78697986ab1ac95dcca4d70/src/core/drive/history.js#L45

So it should be:
```js
instantsearch({
  routing: {
    router: history({
      cleanUrlOnDispose: false,
      push: (url) => {
         Turbo.navigator.history.push(new URL(url))
      },
    }),
  },
})
```

The reason why we needed to call both before was because Turbo's push expects a URL object, instead of a string.
