### ISSUE TITLE
All images from previous hits are downloaded and take all available thread

### ISSUE THREAD

**Issue by Shipow** [algolia/instantsearch.js#302]
When typing a long query on a low bandwidth it becomes very slow because the browser wants to finish the download of every images that have been called by the previous queries.

![image](https://cloud.githubusercontent.com/assets/976175/10616793/50e1f08a-7767-11e5-9b7b-1ff68885f059.png)

**Comment by redox** [comment]
@bobylito any idea on that?

**Comment by vvo** [comment]
Not sure this is something we can easily deal with.

Basically the interface is instant and the hit template decide to show images or not (and the hit template is not on our side, it's always a user pref).

So if the hit template as an <img> tag and if the images are really big then if we both want to show results at the first keystroke and be fast then it's hard.

Every solution will be some kind of delay that we wait before showing the hits, or loading the images (lazyload). But it's all based on timers. Since you cannot cancel image downloads.

**Comment by bobylito** [comment]
I do have some ideas, but having templates involved makes them very hacky.

One thing that can be done is after a search, display div or img without src with a placeholder or a color computed in the resultset and then with a delay of some hundreds of ms, update the src or add the image.

Also we could only load the image that are in the viewport.

But honestly I think that could be a different hit widget. ImageHit that could have a template for some rendering of texts, but not for the image which could be only ours to handle.

@vvo it's not that hard, the time for image loading is not expected to be instant so we can without a problem add a few 100's ms (like 200 or 300) which will be enough to know if there is an other keystroke.

**Comment by redox** [comment]
> Also we could only load the image that are in the viewport.

Starting the download when the image is in the viewport is one thing; but are we able to "cancel" the download when it disappears from it? 

You could give a try to https://github.com/jasonslyvia/react-lazyload

**Comment by bobylito** [comment]
No you can't cancel the download of an image, hence the use of a timeout. It's not an XHR.

**Comment by Jerskouille** [comment]
Couldn't we also use lazyload to avoid loading non-displayed images?

**Comment by vvo** [comment]
Yes we are already not loading non-displayed images. The issue here is more about providing a debounce option like realtimesearch was using before with Angular I believe.

So allowing people to debounce the searchBox may be an option for situations like you know you have BIG images and slow connections.

**Comment by bobylito** [comment]
You will get a better feedback when debouncing the display and not the search. Btw I've experimented all that on the demo with the image I made.

**Comment by vvo** [comment]
> You will get a better feedback when debouncing the display and not the search.

Ah nice ok, so we would need to have some sort of "debounceRender" option?

**Comment by vvo** [comment]
Moving to #307
