### ISSUE TITLE
Results are hidden when iOS keyboard is dismissed

### ISSUE THREAD

**Issue by cnbjornsen** [algolia/instantsearch.js#3036]
**Describe the bug 🐛**
Results are hidden when iOS keyboard is dismissed

**To Reproduce 🔍**
1. Install Angolia in Wordpress or Shopify
2. Do a search from Safari iOS
3. Dismiss the keyboard

A live example helps a lot!   We have a simple online template for you to use for your explanations:
http://test.waikiki.dk (Wordpress + WooCommerce)
https://www.blacksnow.dk (Shopify)

**Expected behavior 💭**
When I dismiss the keyboard on my iOS device, I do so to obtain more viewing space. So the expected behaviour is that the results stay put, when the keyboard is dismissed.

**Screenshots 🖥**
![screenrecording_07-17-2018 11-05-39](https://user-images.githubusercontent.com/38555816/42821401-c55863d2-89d8-11e8-8179-f82968cd8920.gif)

**Environment:**
 - OS: iOS 11.4
 - Browser: Safari

**Additional context**
The issue might be due to the fact, that when you dismiss the keybord in iOS, it removes focus from the input field/search form.

**Comment by bobylito** [comment]
Thanks for opening this @cnbjornsen and thanks a lot for providing the details and the video. Those are all super useful. However, I don't this is the correct place for such an issue but no worries let's try to figure it out :)

Let's summon @Jerska to see what he thinks about it :)

**Comment by Jerska** [comment]
Definitely an awesome video to understand where your issue comes from!
This is actually concerning `autocomplete.js`, not `instantsearch.js`, but indeed, let's keep it simple and answer here. [Let's just make sure to not keep this issue opened for too long]

The idea with `autocomplete.js` is that indeed, it will close automatically on loss of focus. This is intended, as this is the behavior we want most of the time.
Mobile keyboards are indeed an issue, but most of the time, you can still scroll the results list and find what you want.
I don't believe there's any way to detect a specific "close keyboard" event.

You basically got it right with
> The issue might be due to the fact, that when you dismiss the keybord in iOS, it removes focus from the input field/search form.

However, in your case, the cool thing is that I believe it's fairly easy to fix.
Indeed, you have an overlay when you click on search. We can exploit it to have the autocomplete only close when the overlay is clicked.
The easiest solution I see for this would be this one:
1. Activate the debug mode of the autocomplete in our Shopify app
   This will prevent the autocomplete from closing when the input loses focus
2. In `algolia_autocomplete.js.liquid`, replace the `appendTo: 'body'` by your overlay: `appendTo: '.waikiki-search > .search-content'`. If I'm not mistaken, when your overlay hides, then the autocomplete should hide at the same time.

**Comment by bobylito** [comment]
Awesome @Jerska 👍 Does that help you solve your issue? @cnbjornsen

**Comment by cnbjornsen** [comment]
@Jerska Sorry I opened the issue in the wrong place - and thanks a lot for providing an answer here.

I will definitely try out your solution asap. The thing is, the Waikiki site is a WooCommerce site. I did some quick digging in the plugin source files as there's no debug option in the WC plugin (yet), but I was unable to find where autocomplete.js is appended.

Could you by any chance provide instructions or give an idea of where to look in the WooCommerce plugin files?

Sorry I did not explicitly state that the solution I needed was for WooCommerce.

**Comment by cnbjornsen** [comment]
@bobylito yeah that’s the one. 👍

**Comment by Jerska** [comment]
You're basically looking for the file configuring the autocomplete. (My guess would be that there should be something like `autocomplete.js`)
In this file, there will be the main call to the library:

```js
autocomplete('xxx', { hint: false }, ...)
```

You'll need to add the `debug` and `appendTo` parameter to it, like so:

```js
autocomplete('xxx', {
  hint: false,
  debug: true,
  appendTo: '.waikiki-search > .search-content'
}, ...)
```

**Comment by Jerska** [comment]
My belied after looking at the code is that the file you're actually looking for is `templates/autocomplete.php` : https://github.com/algolia/algoliasearch-wordpress/blob/97e1d3e2f77c72d35f12e5298b052c25cd0d7442/templates/autocomplete.php#L144-L152 .

**Comment by cnbjornsen** [comment]
@Jerska You're the boss! Thanks a bunch. That did the trick! Thanks a lot for responding so quick - it is much appreciated.

**Comment by Jerska** [comment]
Happy to read that it solved your issue!
Thanks for having kept us updated!
