### ISSUE TITLE
Can hierarchicalMenu always show the parent

### ISSUE THREAD

**Issue by Asahro** [algolia/instantsearch.js#3047]
Can hierarchicalMenu always show the parent if the data is zero ?
I want to make my hierarchicalMenu always show up

**Comment by bobylito** [comment]
Hi @Asahro thanks for opening this issue. 

Unfortunately this is not possible because the widget is rendered based on the data from the search. Have you had a look at the [connector](https://community.algolia.com/instantsearch.js/v2/connectors/connectHierarchicalMenu.html), maybe you can work something out with it?

**Comment by Asahro** [comment]
I heard that V3 can do this, can I know where to fint v3 and sample of it ?

**Comment by Haroenv** [comment]
Hey @Asahro, not sure where you got this information, but there's on v3 of InstantSearch.js and we don't have this feature planned yet. Hope that makes sense

**Comment by Asahro** [comment]
ohh i see, so the information is wrong, thank for your answared

**Comment by bobylito** [comment]
> ohh i see, so the information is wrong, thank for your answared

How did you get the information?

**Comment by Asahro** [comment]
I read this from this github comment who ask same question
