### ISSUE TITLE
Pagination option maxPages set to zero no longer hides individual pagination items

### ISSUE THREAD

**Issue by jasonbell** [algolia/instantsearch.js#3060]
**Describe the bug 🐛**
Since updating to 2.10.0, using `maxPages: 0` in the Pagination widget no longer works to hide all of the rendered pagination items.

**To Reproduce 🔍**
1. Go to https://capacitype.github.io/prototype-gulp/
2. See visible "1" in between the previous and next arrows in the bottom left of the UI.
3. Compare to https://www.capacitype.io/embeds/tyr/main/ which uses the same widget configuration
4. See no "1" pagination item rendered

**Expected behavior 💭**
In our current version, we wanted to have prev/next to move through the pages while not showing the individual pages. Setting the `maxPages` option to `0` was giving us this. In testing v2.10.0, this same configuration no longer hides the individual page items as desired.

**Screenshots 🖥**

* Looks good v2.3.3: https://d.pr/i/MGqC2z
* Not so happy v2.10.0: https://d.pr/i/7VleSl

**Additional context**

Here is the relevant bits of widget implementation that tries to hide the individual page items, leaving just the prev and next links (shown as icons here).

```
// Pagination widget
  const searchPagination = instantsearch.widgets.pagination({
    container: '#pager',
    maxPages: 0,
    padding: 0,
    showFirstLast: false,
  });
```

**Comment by Haroenv** [comment]
Hmm, I think the previous behaviour actually wasn't the correct one, since it's supposed to limit the last page to go to, so it's surprising that this gives you the experience you wanted. 

I can definitely see the use case for showing only the pagers though. One option is to use the connector to make your own, the second option is that we should consider an option to have the behaviour you want; maybe padding: -1 ?

**Comment by bobylito** [comment]
> the second option is that we should consider an option to have the behaviour you want; maybe padding: -1 ?

Yes and we could even consider a boolean flag for hiding the numbers the same we do with the buttons. WDYT?

**Comment by Haroenv** [comment]
yes, a direct new option also seems like a valuable option to me.

**Comment by jasonbell** [comment]
I was kind of expecting to hear that the original behavior was the real bug. A more direct boolean option sounds great. Using negative value on the padding option would be fine but less clear and obvious. 

In the meantime we’ll see if we can make a custom version using the connector. Thanks!

**Comment by Haroenv** [comment]
We  have not heard from more requests for this feature since, which is why it seems not necessary to add it as an option unfortunately. Luckily you can do two things:

1. make a  custom pagination component which only shows next & previous
2. hide the pagination with css

An example of that second approach is here: https://codesandbox.io/s/instantsearchjs-app-tmc2g

```css
.ais-Pagination-item--page {
  display: none;
}
```
