### ISSUE TITLE
Using this Version on vue.js

### ISSUE THREAD

**Issue by Asahro** [algolia/instantsearch.js#3066]
I am try using vue js and i want to use algolia, I had try the vue version but I think more flexibel from js version. Can this version using in vue js ?
and is there any of the documentation about it

**Comment by bobylito** [comment]
Hi @Asahro, thanks for opening this issue. We definitely [recommend using vue-instantsearch](https://community.algolia.com/vue-instantsearch/) for building your UI with vue. We are in the process of migrating vue-instantsearch to use instantsearch.js at its core but I can't give you any release timeline for the moment.

If you really want to go on this road, you could check the old guide that shows how to [integrate instantsearch.js with angular](https://community.algolia.com/instantsearch.js/v2/guides/angular-integration.html) (but since then we've built angular-instantsearch) or have a look at the [WIP branch on vue-instantsearch](https://github.com/algolia/vue-instantsearch/tree/feat/connectors).

If you have other questions, feel free to open a new issue.
