### ISSUE TITLE
Default theme causes white text on white background on dark GTK+ theme

### ISSUE THREAD

**Issue by Majkl578** [algolia/instantsearch.js#3075]
**Describe the bug 🐛**

Dark GTK+3 (used on Gnome specifically) theme set dark-grey background with white text.
This library sets background to white explicitly, but does not set font color, resulting in _white on white_.

**To Reproduce 🔍**
1. Install Gnome 3
2. Enable GTK+3 dark mode (if not enabled)
3. Create a searchbox input
4. Type text into the input

**Expected behavior 💭**
Either don't change background color or also appropriately change font color.

**Screenshots 🖥**
Default dark GTK+3 behavior:
![](https://user-images.githubusercontent.com/144181/44470373-c6900f80-a629-11e8-8385-959171860baa.png)

With instantsearch.js:
![](https://user-images.githubusercontent.com/144181/44470351-bd06a780-a629-11e8-84b4-7bd00768d145.png)

**Environment:**
 - OS: Linux, Gnome with dark GTK+3 theme
 - Browser: Firefox
 - Version: 62

**Comment by Haroenv** [comment]
Good call, thanks! We should probably _not_ change the background color I think

**Comment by bobylito** [comment]
Since it's not instantsearch.js is not using the common them of InstantSearch just yet, we need to fix that internally first.

**Comment by Majkl578** [comment]
Thanks, I'm probably not the right guy for _any_ frontend, maybe @senseexception would like to pick this up? :wink:

**Comment by Haroenv** [comment]
It actually would be as simple as removing 

https://github.com/algolia/instantsearch.js/blob/62bac743ab3aa679a4e5f10c6e8534b43e80ffcf/src/css/theme/_search-box.scss#L12

or adding `color: $black` after it

**Comment by SenseException** [comment]
Okay, looks like a no-brainer that won't take much time.

**Comment by SenseException** [comment]
I guess we should choose to add `color: $black` instead of removing the background color. In case of websites, that only implemented their own text color but not a background color, removing `background: $white` might result in similar problems as described by @Majkl578.

If we keep `background: $white`, the compatibility is still given for those who didn't configured their own background color. Adding `color: $black` will keep the search-box text readable for every desktop theme.
For the integration on a website, the colors should be set anyway by the designer to prevent off-colored results.

**Comment by bobylito** [comment]
That sounds reasonable @SenseException, adding `color: $black` seems to be the way to go 👍
