### ISSUE TITLE
Question on the page "connectInfiniteHits"

### ISSUE THREAD

**Issue by yogeshR5** [algolia/instantsearch.js#3077]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[connectInfiniteHits](https://community.algolia.com/instantsearch.js/v2/connectors/connectInfiniteHits.html)".

Infinite hits Initially data are loading correctly but when I click LOAD MORE button duplicate data are displaying.it is occurs in some scenario's Ex: when I search test data's are loading but when I click LOAD MORE button that time only displaying Duplicate or repeated Data's

**Comment by samouss** [comment]
Which version of InstantSearch are you using? This issue has been fixed in the version [2.7.5](https://github.com/algolia/instantsearch.js/blob/develop/CHANGELOG.md#275-2018-05-28). In case your version is lower than this one could you try to update the version? Otherwise could you provide us a working example of the issue? It will help a lot to better understand the problem. Here is [a template](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js).

**Comment by bobylito** [comment]
@yogeshR5 Any information would be very welcome 🙏 😁

**Comment by yogeshR5** [comment]
when I click Load More button I simply passed the pros (this.props.refine). it's not loading next 5 lists it reloads the entire list. this was the problem i think.

**Comment by bobylito** [comment]
It's expected that `hits` contains both the last pages and the previous ones.

> The aggregated matched hits from Algolia API of all pages.

Let us know if you have other questions.
