### ISSUE TITLE
Question on the page "Create a calendar widget"

### ISSUE THREAD

**Issue by codetopixels** [algolia/instantsearch.js#3089]
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[Create a calendar widget](__LOCATION__)".

I am struggling to get this to work when my date is within an array. My data is coming from craft cms and therefore outputs like so;

"eventDate": {
        "localeDate": "5/12/2017",
        "localeTime": "2:30 PM",
        "nice": "May 12, 2017, 2:30:00 PM",
        "mysql": "2017-05-12 14:30:00",
        "cookie": "Friday, 12-May-2017 14:30:00 UTC",
        "timestamp": "1494599400"
      },

I think the issue is due to the **eventdate.timestap** being a **string** rather than **numeric** value. Is there a way I can change this when being assigned to the **attributeName**. Thank you!

**Comment by Haroenv** [comment]
Hey! This is a change you would need to do on the indexing side; to be sure it’s able to be used as a range. Unfortunately that means reindexing, this time with the time stamp as a number. 


I’ll close this issue for now, since it’s an issue with craftcms rather than InstantSearch, but feel free to comment still if this isn’t clear to you
