### ISSUE TITLE
Duplicate facets inside the request

### ISSUE THREAD

**Issue by samouss** [algolia/instantsearch.js#3278]
Original Vue InstantSearch issue: https://github.com/algolia/vue-instantsearch/issues/587 

The issue seems to come from the [`enhanceConfiguration`](https://github.com/algolia/instantsearch.js/blob/develop/src/lib/InstantSearch.js#L484-L510) function that compute the initial search parameters. Inside this function we do a union on of both value when it's an array. It can leads to duplicated value like we have inside this issue. In most cases the problem won't be visible unless in that case with the hot reload.

https://github.com/algolia/instantsearch.js/blob/1e86b2e74064c2334f2eb3c8793c3250b78fe27b/src/lib/InstantSearch.js#L496-L498

cc @dulnan

> https://codesandbox.io/s/1qoq47086j

-----

**Bug 🐞**

### What is the current behavior?
When using an ais-refinement-list and ais-menu, while also having routing (using historyRouter and simpleMapping) enabled, the hierarchical facets are added multiple times to the search parameters.

A small CodeSandbox showing this behavior:
https://codesandbox.io/s/9324rjjz3p
Upon page load, using the browser's network activity inspector, the request to Algolia servers shows that `categories` has been added to `facets` twice.

The bug is especially noticeable when working locally, as every time one changes something in a Vue file and a refresh happens, the duplicated hierarchical facets are duplicated again. Which, due to routing with state mapping being enabled, will result in the app hanging for several seconds or even crashing.

![image](https://user-images.githubusercontent.com/4155003/48899719-a0f4eb00-ee50-11e8-8ffe-45eb49314304.png)
![image](https://user-images.githubusercontent.com/4155003/48899727-a6523580-ee50-11e8-9f36-ae9df2c31cd1.png)

This can best be reproduced by opening components/Facet.vue and adding a line break in the template, so a refresh happens.

### What is the expected behavior?
The hierarchicalFacets should only be added once.

### Does this happen only in specific situations?
When using ais-menu or ais-refinement-list together with routing enabled.

### What is the proposed solution?
Unfortunately I haven't figured out exactly where the bug is coming from.

### What is the version you are using?
2.0.0-beta.1

**Comment by msassa** [comment]
Hello, is any advance on this?

I have a similar problem, but is crashing the entire app.

I have prepared this example, where I am adding a button to show / hide the menu.

[![Edit Check extra request](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5k08ro4mqk?fontsize=14)

![image](https://user-images.githubusercontent.com/570080/56298304-4febd900-6108-11e9-87f4-9dddde626123.png)

This is a simplified example, but I found in the real application, that after several clicks on that button, Chrome crash.

And it is because every time I click on the button, multiple requests are made to the algolia api.

![image](https://user-images.githubusercontent.com/570080/56298483-993c2880-6108-11e9-8bf7-59d5c7311996.png)


And in each of them, the 'facets' parameter is duplicated

![image](https://user-images.githubusercontent.com/570080/56298530-ac4ef880-6108-11e9-9b77-6376bdf92040.png)

![image](https://user-images.githubusercontent.com/570080/56298437-7f9ae100-6108-11e9-8d46-4f16b8b14083.png)


After dismantling the entire application, and reassembling it component by component, I discovered that this is caused by the ais-configure

Without ais-configure this doesn't happen, and as you can see in the example, is a simple:

`<ais-configure :hits-per-page.camel="4"></ais-configure>`

Can someone help me solve this, please?

Thank you

**Comment by samouss** [comment]
Hi @msassa, we've provided a workaround on the Vue InstantSearch [issue](https://github.com/algolia/vue-instantsearch/issues/663). Take a look if it can help!

**Comment by msassa** [comment]
Thank you so much !! 
I will continue the feedback in the #663 if you are ok
