### ISSUE TITLE
Autocomplete search component

### ISSUE THREAD

**Issue by corentin-gautier** [algolia/instantsearch.js#3307]
Hi,

I'm looking for a way to display suggestions on a search field, I saw that you have a autocomplete.js library but it looks outdated. I saw that there is a connectAutocomplete connector in instantsearch.js but the documentation about how to implement it is also outdated (404 links).

Do you have any examples of a implementation of an angular 2+ / ssr / autocomplete search ?

Thanks !

**Comment by francoischalifour** [comment]
The link was fixed in the code. You can see the new documentation on the [Algolia website](https://www.algolia.com/doc/api-reference/widgets/autocomplete/js/).

We wrote a [guide for Angular InstantSearch](https://www.algolia.com/doc/guides/building-search-ui/resources/ui-and-ux-patterns/in-depth/autocomplete/angular/) to leverage this connector.
