### ISSUE TITLE
[connectSortBy] avoid to throw an error when the index does not exist

### ISSUE THREAD

**Issue by samouss** [algolia/instantsearch.js#3397]
**Describe the bug 🐛**

The current implementation does throw an error when the current index is not in the list of provided indices. It can be an issue with the URL sync. It's easy for a users to mistyped the name of the index. The errors throw and block the render of the InstantSearch App.

> https://rrz1pyz83n.codesandbox.io/?sortBy=instantt_search_price_asc

**Expected behavior 💭**

Fallback to the default index when the current one does not exist?

**Additional context**

> https://discourse.algolia.com/t/how-to-catch-errors/6938

**Comment by Haroenv** [comment]
🤔 it would also make sense to have a better error catching mechanism IMO

**Comment by yudawp** [comment]
same with my problem, i already declarated and follow step by step from documentation but Cannot read property 'connectSortBy' of undefined. i create custom widget in my custom js. can tell me how to fixed the my problem

**Comment by francoischalifour** [comment]
Hey @yudawp, it doesn't seem like your problem is related to this issue. You can find the documentation for [`connectSortBy` on the Algolia website](https://www.algolia.com/doc/api-reference/widgets/sort-by/js/#connector). Note that connectors are available on the `instantsearch.connectors` object, not `instantsearch.widgets`.

If this doesn't help, please [create another issue](https://github.com/algolia/instantsearch.js/issues/new/choose) so that we don't lose the focus of this original thread.
