### ISSUE TITLE
How to make multiple selections with connectHierarchicalMenu? I know the feature is not available at the moment but is there a way to create a customised connector to achieve this? And how easy is to create a connector for the issue?

### ISSUE THREAD

**Issue by vinothpro** [algolia/instantsearch.js#3466]
**Describe the bug 🐛**

**To Reproduce 🔍**

A live example helps a lot!   We have a simple online template for you to use for your explanations:

https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js

**Expected behavior 💭**

**Screenshots 🖥**

**Environment:**
 - OS: [e.g. iOS / windows / mac / android]

**Additional context**

**Comment by samouss** [comment]
Currently it's not possible to implement a Hierarchical Menu with multiple selections within a custom widget. We use a library internally called the [Helper](https://github.com/algolia/algoliasearch-helper-js) to manage hierarchical facets. This lib does not support multiple refinement for the hierarchical facet. It's something that we have on our roadmap but we don't have any other precision.

For the moment the only solution is to look at how the Helper manage the hierarchical facets. From that you can create a version that supports multiple selections. Unfortunately this is the only solution we have. I'll close this issue since it's already tracked #1658 .
