### ISSUE TITLE
Can I implement fixed columns in infinite scroll Hits?

### ISSUE THREAD

**Issue by Lovely-Fellow** [algolia/instantsearch.js#3487]
Hello.
I have cutomized infinite scroll hits just like following url.
https://codesandbox.io/s/k5y1z5kq73

And I can see the fixed column table from following url.
https://datatables.net/extensions/fixedcolumns/examples/initialisation/left_right_columns.html

Now I'm going to make infinite scroll hits with fixed column, so I have tried just lik follwoing url.
https://codesandbox.io/s/4rz18j8929

But now working well, as I want.
Now infinite scroll is working only for unfixed columns.
How can I make infinite scroll Hits with fixed columns perfectly?
Thank you in advance.

**Comment by tkrugg** [comment]
Hi @Lovely-Fellow 
In your example showMore function is not called when you reach the bottom of the DataTable  because the sentinel is outside the scrolling area of that data table. 
The DOM element of your sentinel need to be invisible on the view port then revealed as we scroll down the DataTable.

It's not clear to me whether DataTable can support a sentinel inside the scrolling area, but there seem to be something that allow for server-side loading of data.  https://datatables.net/extensions/scroller/examples/initialisation/server-side_processing.html
If you can manage to get DataTable to call `lastRenderArgs.showMore()`, it should work as expected.

**Comment by samouss** [comment]
I'm closing this issue because it's inactive since a while. Feel free to open a new one!
