### ISSUE TITLE
Algolia webcomponents

### ISSUE THREAD

**Issue by paales** [algolia/instantsearch.js#3581]
**Is your feature request related to a problem? Please describe 🙏**
We're using Algolia in a 'classic frontend' (Magento 2) with webcomponents, and thus can't just implement a vue/react component set. We do like all the automatic updating of elements when search queries change. We're essentially looking for a lit-html port of the vue/react libraries.

**Describe the solution you'd like 🤔**
We'd like to have that in a set of proper webcomponents. We're using lit-html ourselves to easily build webcomponents, but we're not really bound to a specific webcomponent library. 

**Describe alternatives you've considered ✨**
We've used the Magento 2 implementation, but since it uses mustache and other custom bindings it essentially becomes its own render pipeline, having multiple render pipelines in the same system costs extra and isn't preferably.

There are some other webcomponents that implement algolia but are usually _very_ limited and don't suit our needs.

**Comment by Haroenv** [comment]
@paales, have you considered using the connectors of InstantSearch.js and wrapping them in web components yourself? Another option is also to wrap the components used here. 

The reason we don't (yet) offer web components by default is because the support level is lower than what we currently offer, and we haven't gotten the question very often. 

What have you tried so far? I'd like to take a look to see how it would be possible to wrap correctly

**Comment by zagreusinoz** [comment]
I'm running into a similar issue, Vue has the ability to compile to web components or custom elements, so on the face of it, this should work for me.  However because the widgets needs to be wrapped within the <ais-instant-search> component then I can't separate the widgets I need out to use in my environment as I like.

Now, my use case is quite unique because I'm working to create widgets that work in a low code platform so the widgets need to work independently.

**Comment by Haroenv** [comment]
Our widgets will always need to be wrapped inside a `ais-instant-search` widget for Vue, because it relies on the component tree for URL reconciliation, for a multi-root solution; InstantSearch.js is better @zagreusinoz. 

Can you list what you already have made so we can help out to see how it could be possible?

**Comment by francoischalifour** [comment]
The way we render widgets in InstantSearch.js right now cannot be decoupled from the library lifecycle. The widgets' templates expect strings in return and inject them in our internal Preact components. Thus, it's not possible to use `lit-html` to control the full rendering.

It is however possible to create a web component InstantSearch flavor based on the [connectors](https://www.algolia.com/doc/guides/building-search-ui/widgets/customize-an-existing-widget/js/#anatomy-of-a-connector).

**Comment by davie-robertson** [comment]
bumping this because custom web components are now a thing and supported on all browsers and a vanilla JS/TS component would make like so much easier - https://developer.mozilla.org/en-US/docs/Web/API/Web_components

**Comment by Haroenv** [comment]
@davie-robertson We've explored it multiple times in the past, but the methods of passing parameters (many of which are functions) as well as the interaction with InstantSearch, index and other widgets was much less straightforward than the vanilla js (or framework) integrations. 

What pseudo-code would you like to use more than the current vanilla js interface?
