### ISSUE TITLE
Is it possible to refine multiple attributes?

### ISSUE THREAD

**Issue by AshPowell** [algolia/instantsearch.js#3825]
I have a start_date and an end_date on each of my search items.

What I'm trying to achieve is the ability to filter items by 'Pending', 'Active', and 'Expired'

Pending: start_date > now
Active: start_date <= now AND end_date > now
Expired: end_date < now

I can't figure out how this is possible with InstantSearch.js - any help would be appreciated, 

Thank you!

**Comment by Haroenv** [comment]
Which kind of UI are you looking for this?

**Comment by AshPowell** [comment]
In regards to the filtering of the items, I don't mind building custom - just radio button toggles I guess. Just unsure how to achieve it with any instantsearch.js type widget

**Comment by Haroenv** [comment]
This is indeed something that I don't see as possible with our current widgets, and has come up before (a while ago) in the context of dates. In this case this seems very similar (exactly the same) as a numeric menu, but with multiple attributes. I'd suggest you also start that way:

1. fork https://github.com/algolia/instantsearch.js/blob/develop/src/connectors/numeric-menu/connectNumericMenu.js
2. read from the item instead of the attribute given in the argument

https://github.com/algolia/instantsearch.js/blob/develop/src/connectors/numeric-menu/connectNumericMenu.js#L273

3. add the key `attribute` to each of the options

**Comment by AshPowell** [comment]
Ah ok thanks for your help
