### ISSUE TITLE
Add unique selector to items in refinementList

### ISSUE THREAD

**Issue by Shipow** [algolia/instantsearch.js#383]
I want to add some css to my facets links, so I need unique selector.
![image](https://cloud.githubusercontent.com/assets/976175/10811530/17c193a8-7e0d-11e5-86be-85ae02f33c1d.png)
Since Hogan doesn't support lambdas, I don't really see how I can manipulate the value in my template.
A solution could be to map the facets but I think the widget could help me to achieve this common use case.
![image](https://cloud.githubusercontent.com/assets/976175/10811651/7ecfaac0-7e0e-11e5-86dc-f9cc214c91f8.png)

**Comment by redox** [comment]
Not sure I'm following, what don't you use something like:

```css
#myfacet-container .ais-refinement-list--item label {
}
```

**Comment by Shipow** [comment]
I need a specific class on each item based on its content.

Result should looks like:
<a class="item-epic"> Epic </a>
<a class="item-rare"> Rare </a>
<a class="item-safe-for-css"> Safe for CSS </a>

**Comment by vvo** [comment]
You can use either:

```js
{
  templates: '<a href="{{url}}" class="..." data-facet-value="{{name}}"><span>{{name}}</span>...'
}
```

Then

```css
.list-group-item[data-name="facet name"] {

}
```

So that you do not even have to do a mapping between facet names and "safe css" class/id.

Would that work?

Otherwise, you can use `transformData: function () {}` which allows you to modify the data passed to the template and you could generate your css safe name here.

**Comment by Shipow** [comment]
yes it works.

**Comment by pixelastic** [comment]
This would work, but `[attr=value]` selectors are known to be slow. Not sure if its measurable on such a small list, though.

I would use `transformData`, this is what it is made for: adding custom values to the template.

**Comment by Jerskouille** [comment]
> Since Hogan doesn't support lambdas

RTFM ;) https://github.com/algolia/instantsearch.js#template-configuration
We fixed Hogan lambdas in `instantsearch.js`.

But I agree with *vvo* and *pixelastic*, that's exactly what `transformData` is all about.

**Comment by vvo** [comment]
> This would work, but [attr=value] selectors are known to be slow. Not sure if its measurable on such a small list, though.

Yes, first we use it, and if it's slow we see what to do. I could not find any good recent reference stating attribute selector inside a css file is slow.

**Comment by pixelastic** [comment]
The better reference I have is [CSSWizardry](http://csswizardry.com/2011/09/writing-efficient-css-selectors/) based on [Steve Souders](http://stevesouders.com/efws/css-selectors/csscreate.php). This is from 2011 but I don't think the inner engine of CSS parsing changed that much since. We still parse rules from right to left, so the key selector (the rightmost) should be as specific as possible.

Also note that if the value you add to the `data` attribute contains `"` you might have to escape it. `transformData` is safer.

**Comment by vvo** [comment]
> This is from 2011 but I don't think the inner engine of CSS parsing changed that much since.

I would really be disappointed if the browser developers did not make any significant performance improvement of CSS parsing inside browsers for 4 years! But ok maybe.

Event the article says "Browsers will only ever get better at CSS parsing speeds, even mobile ones. You are very unlikely to ever notice slow CSS selectors on a websites but…"

will see!
