### ISSUE TITLE
Get state and post to page 

### ISSUE THREAD

**Issue by JonnyBR12** [algolia/instantsearch.js#3839]
Hi All! We've upgraded from V2 to V3 and hit a snag. Previously, we had a search function on the homepage, we'd grab the state and then on button click we'd then go to another page and show the results. 

Now we've upgraded, when we post to the page, the results aren't showing, instead it doesn't sync. I've been reading the docs and trying to figure out what I've done wrong / or not changed inline with the new version but can't see anything. 

If anyone can point me in the right direction, that would be a huge help.  

I've got the following so far:

    routing: true,
        searchFunction: function(helper) {
        var state = helper.getState(['query', 'attribute:*']);
        var qs = algoliasearchHelper.url.getQueryStringFromState(state);
        $('#search-button').on('click', function(){
            window.location.href = "/product-page?" + qs;
        });
        helper.search();
    },

**Comment by samouss** [comment]
Hi, before the upgrade which routing system was in place? The modern implementation: `routing` or the legacy one: `urlSync`? I ask the question because the two system does not use the same strategy for the serialization of the URL. The output of `getQueryStringFromState` is not compatible with the modern `routing` system. We don't use the Helper anymore to generate the URL. Those function on the Helper are deprecated and will be removed in the next major.

InstantSearch exposes on its instance a top-level function called `createURL`. This function has almost the same purpose than the function you're using. You should be able to use it rather than the legacy `getQueryStringFromState` function.

**Comment by JonnyBR12** [comment]
Hey @samouss, thanks for the reply (sorry for taking so long to get back to you!). 

Ah, we were using urlSync so I see what you mean and thanks for the example too. Much appreciated. I'll have a good read and check it out.
