### ISSUE TITLE
Sort By Drop-down doesn't has Selected attribute for Options

### ISSUE THREAD

**Issue by sandeep570** [algolia/instantsearch.js#3855]
In the Sort By Drop-down for the options the selected attribute is missing I mean "selected=selected".

**Steps to reproduce the behavior:**
In any Page which has Sort By Drop-down then select any options then the HTML attribute called "selected=selected" is not set.

**Expected behavior **
If we select any options then the "selected=selected" has to be set for options.

Could anyone please help me out.

**Comment by samouss** [comment]
The **attribute** is not set but the underlying **property** is actually set. You can inspect the selected element from the console. You'll be able to see that `node.selected` returns `true` for the selected option and `false` otherwise. Do you have a specific use case that requires the `selected` attribute to be present on the element?

Note that HTML attribute and property are not the same. You can find more information about that on this [StackOverflow](https://stackoverflow.com/questions/6003819/what-is-the-difference-between-properties-and-attributes-in-html) post.

**Comment by sandeep570** [comment]
Hi @samouss thanks for the reply and yes I need the `selected` attribute to be present on the element. Using jquery on change I need to get the value which has the `selected` attribute.

Is any other way that without using selected attribute I can get the user selected option all times?

**Comment by samouss** [comment]
You can use the event emitted on `change` to retrieve the selected element. Here is an example with jQuery (see below). Is it what you want to achieve? If not please provide a bit more context about or an example.

```js
$("select").on("change", event => {
  const selectedValue = event.target.value;
  // ...
});
```

**Comment by sandeep570** [comment]
Hi, @samouss greeting for the day. I did the same way to get the selected value but why the algolia is not adding selected attribute in default behavior. Because using that selected attribute value getting option value is easier than adding an extra jquery code. Ok thanks, I will try this code and let u know my feedback.
