### ISSUE TITLE
SearchBox#onReset test no longer passes

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#4160]
see https://github.com/algolia/instantsearch.js/pull/4156#discussion_r331552971

It seems like the `reset` event no longer is triggered after migrating to preact X, the tests have been updated, but the event doesn't get called correctly

https://github.com/algolia/instantsearch.js/blob/92a21308a272e391de726a47bfaf84e794077697/src/components/SearchBox/__tests__/SearchBox-test.js#L288-L345

We suspected JSDOM initially, but it seems the event does get fired. This means it's enzyme which doesn't trigger the event correctly.

**Comment by francoischalifour** [comment]
The reason why the test fails is that the `reset` event is not fired in Jest 24 because it relies on jsdom 11 which has an issue with form resets ([see jsdom changelog](https://github.com/jsdom/jsdom/blob/master/Changelog.md#1310)).

This will be fixed as soon as Jest 25 is released because they'll upgrade to jsdom 15 ([see Jest changelog](https://github.com/facebook/jest/blob/master/CHANGELOG.md#chore--maintenance)).
