### ISSUE TITLE
when binding events to document, in some cases, event.target is not bound to the DOM

### ISSUE THREAD

**Issue by e-krebs** [algolia/instantsearch.js#4201]
**Describe the bug 🐛**
when clicking a checkbox inside the `refinementList` widget, the triggered event sometimes has a event.target not being bind to the DOM.

**To Reproduce 🔍**
Let's say you have `document.addEventListener('click', myFunction)` (with `myFunction` being defined).
You create an instantsearch with a `refinementList` widget.
You clic multiple time on that widget's first checkbox.
Each time you do so, `myFunction` is called with an `event` object.
After the first time it is called, the `event.target` that `myFunction` receives is not bind to the DOM

Live example:
https://codesandbox.io/s/ais-ecommerce-demo-app-g06se
_Look at the Console logs_

**Expected behavior 💭**
The `event.target` should always be binded to the DOM.

**Environment:**
 - Browser at least chrome
 - Version at least latest (78 at time of writing)

**Comment by tkrugg** [comment]
Hi @e-krebs 
we don't guarantee we reuse the DOM across renders (destroying or reusing DOM is decided by our component abstraction Preact).

Here when you click on a DOM element, we mutate the DOM and sometimes destroy the checkbox instead of reusing it. 
If you want to hook some specific behaviour to the component after a refine call, I would advise creating your own component on top of the connector, so that you have full control on the DOM.

I hope this helps. Closing for now but feel free to reopen if i missed something.
