### ISSUE TITLE
Contributing: Explicit the issues -> release workflow

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#424]
I'm still having troube understanding how the issue workflow is working. So instead of pestering @vvo everytime, I think we should write it down in the `CONTRIBUTING.md` file.

Here are a few of the questions I have:

- [ ] When should we close issues? 
- [ ] When should we mark them as "ready for release"?
- [ ] When should we mark them as "in progress"? 
- [ ] Should it be handled through Waffle only or through the GitHub API?
- [ ] How often should we do a release?
- [ ] Document (listing all valid words) the format implemented in https://github.com/algolia/instantsearch.js/blob/master/scripts/validate-commit-msgs.sh#L47

I'm still confused by the number of issues and the latency in display between the time one is solved and the time it is marked as closed in the GitHub issue pages.

**Comment by vvo** [comment]
Answering here so we discuss and agree:

> When should we close issues?

When the fix was released (published in npm)

> When should we mark them as "ready for release"?

When done and waiting for a release, actually I renamed it to "✔️ to be released" (+ green) yesterday, to make it obvious.

> When should we mark them as "in progress"?

When you are working on it (those are waffle flow but this mis just github labels)

> Should it be handled through Waffle only or through the GitHub API?

I think it does not matter, I use waffle because its very handy (waffle url: https://waffle.io/algolia/instantsearch.js)

> How often should we do a release?

Right now its really ANYTIME because we are iterating and do not care, so based on needs and the number of waiting for release items.

Once we are really public, then we should more carefuly think about release.

For big features it should be handled differently because we can sync with a blog post etc.

Still even right now for the JS client and helper, we just release as often as we can when it's small bugfixes/features.

> Document (listing all valid words) the format implemented in

Yes, copy pasting the angular commit guidelines with more details should be enough.

**Comment by pixelastic** [comment]
Thanks, this is clearer. I'll do more releases then, to cleanup a bit.

**Comment by vvo** [comment]
about the "new widget" tag its right now used as both confirmed and unconfirmed widgets so let's not say its only for one or other. It's for both :)

**Comment by vvo** [comment]
Will update the guide now
