### ISSUE TITLE
The `insightsClient` option has not been provided to `instantsearch`

### ISSUE THREAD

**Issue by vickyrathee** [algolia/instantsearch.js#4269]
When I click anywhere on my search result it show a error on console 

**The `insightsClient` option has not been provided to `instantsearch`** 

The same in your netlify example as well - https://instantsearchjs.netlify.com/examples/e-commerce/search/?query=books

**Steps to reproduce**
1. Search anything
2. Click on the search result items

How can I fix this? 

![image](https://user-images.githubusercontent.com/6106479/71242584-46b8a900-2334-11ea-9fbe-385625243d03.png)

**Comment by Haroenv** [comment]
Hmm, this is a good catch. It seems like we removed a condition erroneously, which causes the library  to think insights is always enabled, even while it's not done by the user. See https://github.com/algolia/instantsearch.js/commit/9cac5a3aa4af616ec7913c17ed7388134c5e7f0a#diff-3eeb23719bab17ca03a8f33b4d1df9c5L15-L17 (cc @tkrugg)

For now you can simply  ignore that error message, since it won't impact your search, but this is definitely a bug

**Comment by tkrugg** [comment]
this is fixed here: https://github.com/algolia/instantsearch.js/pull/4254

**Comment by Haroenv** [comment]
This has been released in 4.1.1, thanks for reporting!
