### ISSUE TITLE
Connecting refinement with another indice

### ISSUE THREAD

**Issue by ergra** [algolia/instantsearch.js#4341]
Hi!

I have been searching about this but I havent gotten very far. Basically I am trying to connect my hierarchicalMenu with another indice. Like this:

Right now I have 2 indices. One containing songs, and another one containing taxonomies for the songs (genres).
The song indice also have an attribute called genre, which can connect it to the genre indice.

The genre indices include information about the genre, for example a description of "Rock" and an icon.

I am displaying results from the song indices to the users, with genre as a hierarchicalMenu. However, since this is just a refinement of the "Genre"-attribute, this list is not connected to the Genre indices at all.

So for example, if I wanna display the icon for each genre next to the refinement list, what would be the strategy for this? They both have a matching key which can use to connect the attribute to the entry in the genre indices.

Does anybody know of an example where anything similar is done? Or what is the correct way to approach this.

**Comment by Haroenv** [comment]
Could you make the experience you have now in a sandbox? It will be easier to know what exactly you’re expecting. 
We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch). Thanks!

**Comment by ergra** [comment]
Well the experience I have right now is pretty similar to the sandbox you sent.

In the example you sent there are brands. Right now they are a taxonomy of each product.
So in your example, if you would like to display the logo next to each brand in the refinementlist, how would this be done?

I have indexed another indices containing all the brands. This contains logo, description, etc about each brand. I want to display this information in the refinementlist for my main indices (instant_search in your example).

I've dont know where to start on this functionality so I dont have any code to show you for it, all i've done is index all brands separately.

**Comment by francoischalifour** [comment]
It seems that you followed the principle of [denormalization](https://en.wikipedia.org/wiki/Database_normalization) in your index. Algolia, and other search engines, usually use the [denormalization](https://en.wikipedia.org/wiki/Denormalization) strategy because they support other constraints than most databases (including high performance).

We didn't yet consider the feature you're suggesting because we'd need to make a lot of assumptions:

- Is the index name a valid-enough heuristic to "merge" the facets results?
- Should we target `n` indices every time a query is performed?
- How does this fit in the [Federated Search](https://www.algolia.com/doc/guides/building-search-ui/resources/ui-and-ux-patterns/in-depth/multi-index-search/js/) paradigm?

Another solution that I would have seen and would have expected to work if I was a first-time Algolia user would be to access the images as part of the facet value schema. To my knowledge, there's no easy way to retrieve the images associated with the facet value even if you were to store the image with the refined value in the index (`{ "value": "Samsung", "image": "samsung.svg" }`). This happens because Algolia only returns the faceted value (`"Samsung"`), and not the whole object.

The easiest solution for now would be to facet the strings and to use some pattern matching in the frontend.

**Comment by Haroenv** [comment]
As there was no response, I assume the original issue is fixed now. If you still have problems, please open a new issue with reproduction :)
