### ISSUE TITLE
The documentation for backend search is missing a key information

### ISSUE THREAD

**Issue by katlimruiz** [algolia/instantsearch.js#4441]
## 🐛 Bug description

events.js:62 Uncaught (in promise) Error: Uncaught, unspecified "error" event. ([object Object])
    at y.W.emit (events.js:62)
    at te.<anonymous> (InstantSearch.ts:414)
    at te.W.emit (events.js:81)
    at te._dispatchAlgoliaError (algoliasearch.helper.js:1286)

## 🔍 Bug reproduction

Follow the tutorial, and it gives you the above error
https://www.algolia.com/doc/guides/building-search-ui/going-further/backend-search/js/

## 💭 Expected behavior

Search done and flowing

## Found solution

The piece of info that is missing from the documentation is the fact that the results from 
`index.search` must be enclosed in this way:
```
var objresult = index.search("", {...});
ctx.body = {
  results: [ objresult ]
};
```
If you provide the result directly from index.search you get the above error.

How it was discovered, because the widget showcase and algolia console both have their results enclosed like that.

**Comment by Haroenv** [comment]
Sorry that we haven't replied to this in a while, but I just checked and the guide (here: https://www.algolia.com/doc/guides/building-search-ui/going-further/backend-search/in-depth/backend-instantsearch/js/#on-the-backend-create-the-necessary-routes) seems to be correctly doing `client.search`, while in your code you are doing `index.search`, which isn't the same. 

Since there doesn't seem to be anything wrong with the documentation, there's not really anything we can change there. Hopefully the SEO of this issue should help anyone else confused about this

**Comment by eunjae-lee** [comment]
For those who visit here in the future, unlike `index.search`, `client.search` is actually an alias of `multipleQueries` method.
