### ISSUE TITLE
RangeSlider in doc has a weird behavior

### ISSUE THREAD

**Issue by ElPicador** [algolia/instantsearch.js#446]
1. The first time the component is used, the page automatically scrolls
2. After setting a min value ($1594 in exemple), and put it back to the minimum possible value ($1 in exemple), the last min value is displayed ($1594 in exemple)

![rangeSlider](http://g.recordit.co/brndhottX9.gif)

**Comment by vvo** [comment]
Hi,

Two issues here:
1. the documentation is a live example where all the widgets are working against the same instantsearch instance. And yes it feels really weird that the page is constantly moving on some widgets. To fix this: we could instantiate one instantsearch instance per widget, thus they are no more linked but that is not a big deal at all.
2. The second issue is linked to the 1. in fact, if the slider was the sole widget of a single instance the behavior would be different. What you are seeing here is that the rangeSlider and priceRange widgets are acting on the same attribute (price). This is why this is weird (ref #327)

**Comment by ElPicador** [comment]
Before anything this one needs #450 to be merge

**Comment by bobylito** [comment]
I'm sorry but this bug should be reopen. The problem is that we have incompatible widgets and it doesn't feel right. Actually our kitchensink page that we use in dev has the same problem.

**Comment by vvo** [comment]
@bobylito Aside from that, I have the feeling trying to mix documentation AND live demo (with all widgets belonging to a single instantsearch instance) is not the right thing to do in the end.

We may get used to it us developers since it's like that since the begining. But my first reaction when testing it was "Who! Something is moving behind this widget I am testing, I do not know what but it is moving, down below" => because refining/querying will change the page height.

I guess if I am just starting with the library, if I really want to see a full example I will go to > Examples.

The way the live documentation is done right now can be disturbing for newcomers to the library I believe. Maybe @ElPicador you can share your experience of discovering the documentation was "live".

**Comment by redox** [comment]
> mix documentation AND live demo

I think we've moved forward since the first step. What we want now is a documentation. What is cool is to see the widget; but definitely not to play with the whole "demo".

**Comment by bobylito** [comment]
Cool let's move on and fix the widgets to make them compatible (or at least see if it's possible).

On it!   o/

**Comment by bobylito** [comment]
I found a few issues with numeric related widgets, will create other issues.
