### ISSUE TITLE
Conditionally show/hide a widget

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#455]
I was thinking, we might want to have a way to show/hide the widget depending on a condition.

Let's say that I have two refinementLists. I show the first one by default and want to show the second one only if the first one is refined.

The api could look something like:

```
instantsearch.widgets.anyWidget({
    [...],
    showOnly: function (helper) {
      return helper.getRefinements('first-widget-attribute').length > 0;
    }
  })
```

What do you think ?

**Comment by vvo** [comment]
I think it is time to rething about (not for V1):
- widget instance methods (hide, show, refine from outside?)
- widget events (hide, show, refine event?)
- widget public properties (.container?)

Because your particular need emphasis that this could be handled by a generic API rather than inventing more and more API methods for specific needs.

Ref #83 

What do you think?

**Comment by pixelastic** [comment]
Agreed with @vvo. Next version should have emphasis on event and public methods/properties of container. I feel that this specific use case should be handle by the users, listening to events and interacting with its widgets, but we should give them the flexibility to do so.

**Comment by maxiloc** [comment]
Yes works for me so I am closing this since there is already #83
