### ISSUE TITLE
numericfilters generates an error

### ISSUE THREAD

**Issue by dianos** [algolia/instantsearch.js#4807]
×
Error
[Numeric filters] Can't switch from the advanced to the managed API. It is probably an error, if this is really what you want, you have to first clear the numeric filters.

` numericFilters: ['popularity > 2000'],`
## 🔍 https://codesandbox.io/s/instantsearchjs-app-forked-4ob6g?file=/src/app.js:320-358

**Comment by Haroenv** [comment]
Could you clarify what the goal is with setting the numeric filters, should it be reflected in the UI or not?

**Comment by dianos** [comment]
Hi Haroen, 
Yes it will filter the results. It does work when I set 'filters'. But numericFilters generates an error.  Is there a reason I can't use numericFilters?

**Comment by dianos** [comment]
Ideally I would want it to update the widget as well, if that is what you were asking? But that's a separate issue.

**Comment by Haroenv** [comment]
Based on what you're saying, I think you're looking for initial UI state, not for setting a filter with configure, as you want the UI to be updated as well: https://codesandbox.io/s/instantsearchjs-app-forked-8ic9w?file=/src/app.js

**Comment by dianos** [comment]
yes thanks; I found a different way to accomplish this as well using  disjunctiveFacetsRefinements: {    },  inside configure().   but still curious about 'numericfilters' not working. are you dropping support in favor of 'filters' ?

**Comment by Haroenv** [comment]
What's happening is that the range component you are using actually behind the scenes uses both numeric refinements (not as a string, but as an object, which is what the original warning you got is about) and disjunctive refinements. To avoid you having to learn about those implementation details, we have added the ui state that maps more directly between the widgets and their state rather than search parameters (which could change in a minor version).

Hope that's clear @dianos !
