### ISSUE TITLE
documentation: rangeSlider: add note about automatically configured min and max

### ISSUE THREAD

**Issue by Shipow** [algolia/instantsearch.js#502]
![image](https://cloud.githubusercontent.com/assets/976175/11020697/51e808ba-8627-11e5-8c73-9fc804450cd3.png)

**Comment by vvo** [comment]
@Shipow There's no "min" "max" configuration, it's automatically computed from your data. I think being able to override it is a good idea. And since you opened the issue, it means that it bothered you.

What we could do right now is say "The min and max are automatically computed given your data", that should be sufficient for v1?

**Comment by Shipow** [comment]
Ok not sure it'll bother me, I was just expecting it and didn't really tried the widget.
