### ISSUE TITLE
starRating disappearing once clicked in live docs

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#615]
![star-rating](https://cloud.githubusercontent.com/assets/123822/11183434/fa14c7f8-8c71-11e5-9a12-138c80767033.gif)

**Comment by vvo** [comment]
No error in console

**Comment by Jerskouille** [comment]
I didn't see that coming : The `starRating` widget is actually using the price as a facet. Using `Math.round` works for displaying the values, but obviously doesn't for refining. Should I randomly assign notes to our dataset?
Moreover, should we use a disjunctive numeric refinement and use `myfacet>val` instead of `(myfacet:val,myfacet:val+1,...,myfacet:max)`? It will break implems using strings for their stars but the current implementation breaks with floats, and I think we'll have more float scores than string ones.

**Comment by redox** [comment]
Hmmm, not sure about that. The goal was really to use a facet and not a numerical attribute to ensure the counts & refinements are working. I'll need to check if I have another fix (I was more thinking of removing the `Math.round` and ensure the dataset use `0..5` integer values).

**Comment by vvo** [comment]
This one was done, open another specific issue for what you want to further fix @Jerskouille

**Comment by redox** [comment]
> This one was done, open another specific issue for what you want to further fix @Jerskouille

Thx @vvo
