### ISSUE TITLE
documentation: Links to anchors not always scroll to the correct part of the page

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#664]
- Click on [this link](https://community.algolia.com/instantsearch.js/documentation/#refinementlist) to open in a new tab
- Wait for the page to load in the new tab
- Go to the tab
- The page is not scrolled to #refinementList as it should, but goes to hierarchicalMenu

This is weird, and sometimes reloading the page does not seem to solve it. I think this comes from the anchor.js library we're using, I had the same issue on some of our main documentation pages in the past. Still unsure where it's coming from.

**Comment by vvo** [comment]
Why do we use a library to scroll to anchors?

**Comment by vvo** [comment]
Ah ok sorry the anchor.js is done for the small anchors icons we have

**Comment by vvo** [comment]
Also the anchors are no more showing up when hovering :D

**Comment by bobylito** [comment]
I think it's because we 'optimized' the weight by removing font awesome :P

**Comment by vvo** [comment]
Can't find any reference to anchor.js anymore, are we just using pure anchors?

I can definitely reproduce the bad behavior when opening in a new tab and waiting for it to load.

Maybe we could force the url back again when the tab get focused (if we have an event). That would be a quick and dirty fix.

This bug may be due to the fact that the page height changes when the widgets are initialized.

**Comment by pixelastic** [comment]
> This bug may be due to the fact that the page height changes when the widgets are initialized.

Yep, I think that's the case. Nice catch. Listening to the tab select might work if such an event is easily accessible, or waiting for all the widgets to instanciate before scrolling to the url again.
