### ISSUE TITLE
pagination: buggy first/previous/next/last logic

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#668]
I feel like the logic used to hide/show the various previous/first/next/last links is buggy. Here are some screenshots:

![image](https://cloud.githubusercontent.com/assets/283419/11271018/a7396350-8ec3-11e5-8447-9bec6f94415a.png)
^ I'm on the first page, everything is alright.

![image](https://cloud.githubusercontent.com/assets/283419/11271025/b2b4abb8-8ec3-11e5-846c-4ea1d8dd674a.png)
^ I'm on the second page, I don't think the "<<" (first page) link is needed (redundant with "<" previous)

![image](https://cloud.githubusercontent.com/assets/283419/11271042/cc02a37c-8ec3-11e5-9191-16130d96d074.png)
^ 4th page, everything is alright

![image](https://cloud.githubusercontent.com/assets/283419/11271048/d47b6d18-8ec3-11e5-8749-520d2570f62f.png)
^ 5th page, oops the 6th page link disappeared. And I have both next and last (last might be useless here, and related to #594)

**Comment by vvo** [comment]
I think, the 6th page disappearing is a bug we need to fix (bug)

As for the "I am on second page", we should keep showing the <<, not really a big deal nor something we should again weight our preference I feel.

Others are good as you said

**Comment by Shipow** [comment]
Some thoughts because obvious always win:
- It's not recommended to use only icons most of the time so plain text 'previous', 'first', .. should be default.
- it's  not recommended to hide elements from an ui, so visible + disabled should be the default.
- the current representation does not inform about the total pages (and when all pages are displayed first/last links are redondant, useless and even confusing when not labelled.
- There is a lot of different config for pagination, no silver bullet, it really depends of the usecase.
- I'm personally more often attracted by ellipsis solution (always show 3 first pages, and last one)

**Comment by bobylito** [comment]
Ok let's fix the obvious bug then :)

**Comment by pixelastic** [comment]
Ok, let's keep this issue focused on the 6th page bug then. We'll have to discuss a bit more to see how we want to tackle the other pagination UI questions

**Comment by bobylito** [comment]
Pull request is here : https://github.com/algolia/instantsearch.js/pull/675
