### ISSUE TITLE
Build - Windows

### ISSUE THREAD

**Issue by andymac4182** [algolia/instantsearch.js#706]
If the build scripts could use a cross platform library such as the ones for Node that would be great so this can be built on Windows as well.

**Comment by vvo** [comment]
Hi @andymac4182 indeed this is something we need to adress by using more native JavaScript rather than shell scripts for build.

May I ask you why do you need to build the project locally? Are you trying to fix some bug or add some new features?

We have pre-built versions available on jsdelivr: https://github.com/algolia/instantsearch.js#from-a-cdn

Let me know

**Comment by andymac4182** [comment]
@vvo I was attempting to build it locally as we have a requirement for a geo-search widget that I was going to build and submit back. I am leaving as a separate JS file in my project for the moment but it would be good if this was supported.

**Comment by vvo** [comment]
Ok definitely something we need to address.

Did you so how google maps widget? https://github.com/instantsearch/instantsearch-googlemaps

**Comment by andymac4182** [comment]
I had a look at that. It doesn't fit with what we are looking for.  What we were looking for is find objects within X km using a range slider of IP at the start and eventually using the browser geolocation library for mobile devices.

**Comment by vvo** [comment]
We are not gonna fix this anytime soon. This would require us some good work while we are not at all working on windows at the moment.

I am not saying we will never make it windows compatible, but maybe at somepoint it will be compatible because windows will be happy with the command line.
