### ISSUE TITLE
Possible to change the limit of a refinementList widget real time ?

### ISSUE THREAD

**Issue by chrisvidal** [algolia/instantsearch.js#756]
lets say i limit my brands to 5 values at a start .
then lets say i want to be able to change this limit to 10.
right now i added a show more link in the template footer, and i was hoping to change the limit of the widget and call a render or search event or something.

any idea on how to do that please ?

**Comment by bobylito** [comment]
Thanks @chrisvidal for this issue. Right now we can't easily do that. It implies modifying the refinementList widget as the template system does not allow to make interactions with the search. This is linked to #401 and I will update it to provide an API proposal so that we can work on it for the next release. Feel free to comment there to provide us your feedback on the API :)
