### ISSUE TITLE
[Pagination] when maxPage is not specified it's set to 20

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#761]
```
search.addWidget(
  instantsearch.widgets.pagination({
    container: '#pagination-container',
    scrollTo: false
  })
);
```

Will limit the number of page to 20, this is really weird

I think it is ok to document it like this
```
search.addWidget(
  instantsearch.widgets.pagination({
    container: '#pagination-container',
    maxPages: 20,
    scrollTo: false
  })
);
```

but removing the param should not let the 20 pages limit

**Comment by pixelastic** [comment]
Maybe we could allow a special value of `-1`, meaning unlimited and setting it as the default, while keeping the `maxPages: 20` in the documentation?

**Comment by maxiloc** [comment]
I don't think we need a special value for me it's pretty clear that if you remove it there will be no limit

**Comment by vvo** [comment]
Two things here, we put a default limit because it would make sense most of the time: a result page of 10 hits on 20 pages is already an impressive result list, and few people will want to read 20 pages of results (but the developer testing his implementation).

At the same time, it feels weird that there's a hidden default parameter.

So I propose that at the next major release (i.e. 2.0.0), we remove the default limit and document using 20.

We cannot do this change in a minor release, it could break people's implementations.

**Comment by redox** [comment]
> I don't think we need a special value for me it's pretty clear that if you remove it there will be no limit

Just to be clear, there is always a limit (<1000 hits) and the maxPages should then be computed from the `answer.nbPages`.

**Comment by maxiloc** [comment]
@redox yes sure

**Comment by vvo** [comment]
I had said "in a major release" but that's way too much for such a "minor" change.

It should not trigger anything bad but some users having their website jump from 20 pages to 99.. which should not be an issue
