### ISSUE TITLE
[Hierarchical Menu] Widget does not inform if the item has children

### ISSUE THREAD

**Issue by norok** [algolia/instantsearch.js#767]
The widget does not inform when one of it's item have children. This can be very useful on many types of filters and is a big problem for a page where I implemented it today.

If anyone knows a workaround solution for this, I would love to know how you did it.

**Comment by wundo** [comment]
+1

**Comment by vvo** [comment]
Hi @norok thanks for reporting this. Indeed that would be a nice addition, would you like to contribute?

Have a look at how the underlying React component is doing it: https://github.com/algolia/instantsearch.js/blob/master/src/components/RefinementList/RefinementList.js

Maybe @wundo?

Otherwise, we are taking your request into account and should add it as soon as possible

**Comment by vvo** [comment]
moved to #818
