### ISSUE TITLE
default theme broken

### ISSUE THREAD

**Issue by kky** [algolia/instantsearch.js#788]
I believe the default theme on the [CDN](http://cdn.jsdelivr.net/instantsearch.js/1/instantsearch.min.css) is missing most classes. It has styling for pagination and sliders, but not for search box, hits, etc.

Also note that the default theme pointed to [here](https://community.algolia.com/instantsearch.js/documentation/#custom-themes) returns a [404](https://github.com/algolia/instantsearch.js/blob/master/css/instantsearch.scss).

**Comment by vvo** [comment]
@kky The fact that the default theme as very few rules is normal and on purpose. I know it looks counterintuitive but this was done to avoid any styling collision with the host website using instantsearch.js.

So we deliberately choosed to have a very RAW theme and let useres do their own theming by overriding classes.

That's why we still have all the css classes defined but empty in the unminified version: http://cdn.jsdelivr.net/instantsearch.js/1/instantsearch.css

I will try to explain this in clear words in the documentation and fix this 404.

Thanks a lot for the feedback.

**Comment by vvo** [comment]
Moved to #819
