### ISSUE TITLE
new searchBox option: queryHook

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#817]
```js
searchBox({
  // called everytime we would do a search request
  queryHook: function(inputValue, search) {
    return true; // do the search request
    // return false; // don't do the search request
    // search(); // you can call this to do the search with the provided query that would have done a search request
  }
});
```

This will solve #776.

@hkdobrev I am not sure to get the use case of being able to replace the query when calling search() as you proposed in https://github.com/algolia/instantsearch.js/issues/776#issuecomment-173373658.

Can you tell us more about the use case? I am not talking about https://github.com/algolia/instantsearch.js/issues/4#issuecomment-173337033

**Comment by hkdobrev** [comment]
@vvo I may need to implement something with instant search which is not set in stone yet, but here is an overview:

- A visitor searches with the term "chair" typed in.
- Then they search for a brand by appending the brand name "Acme".
- The search term is "chair Acme" now.
- We can detect that and recognise it as a brand name and trigger a search for the term "chair", but filtered by the "Acme" brand.

This way we would filter by the brand with certainty instead of showing chairs not from the Acme brand down the search results when these results include the "Acme" word in the description. We have the unfortunate scenario where search by brand name is pretty important, but at the same time we have a lot of brands named after objects, colours and materials such as "wood", "blank", "red" etc. and the word - one-letter brand names.

**Comment by vvo** [comment]
Ok so for this particular use case, do you think #823 could do it more easily?

**Comment by Jerskouille** [comment]
Do we even need to return anything ? (I find it weird to mix both return values and callbacks)

```js
return inputValue.length > 3;
```
vs

```js
if (inputValue.length > 3) search();
```

**Comment by vvo** [comment]
> I find it weird to mix both return values and callbacks

Me too!

Indeed your solution is better, thanks!

**Comment by hkdobrev** [comment]
@vvo Yes, #823 would be great!

However I think `queryHook` and `beforeSearch` hooks could be combined. They would be triggered at the same stage, correct? So we could have only one hook which could either cancel or modify the search or do nothing.

**Comment by vvo** [comment]
I think they are somehow different, queryHook allows you to decide to do or to not do a search given a keypress.

beforeSearch allows you to modify the search state before it is sent, but you can't cancel the search completely.

If we make beforeSearch able to decide to not do any request then it would mean that as soon as you use beforeSearch, you wil be responsible for calling helper.search(). That's doable but wonder if it's easier. What do you think?
