### ISSUE TITLE
urlSync perf issue on Chrome

### ISSUE THREAD

**Issue by olance** [algolia/instantsearch.js#827]
Chrome has troubles updating the URL as often as it can get when typing in the searchbox, resulting in a very slow/laggy search experience.

We don't really need the URL to be updated at each keystroke (who wants to click the back button 10 times after typing a 10-letter query?), so the best solution could be to sync the URL only when the searchbox is blurred?

Or at least debounce the URL update to avoid changing it too often.

**Comment by hkdobrev** [comment]
Debouncing was discussed in #776 and could be solved via #817.

Also I think typing with urlSync already updates the URL with `replaceState` rather than `pushState` which eliminates the back button problem. See http://community.algolia.com/instantsearch.js/examples/media where when you type fast this pushes only a single state in the browser history which gets replaced on subsequent characters. Only after you stop typing for a moment it would push the next characters in a new state.

**Comment by bobylito** [comment]
@hkdobrev is right, the URL is updated but new entries in history are only created when a certain amount of time is passed. This is platform related and even not reproducible on all OS.

From our tests, UX wise, debouncing is far from perfect as it is not very predictable when you don't know the implementation. As for listening to the change or blur event, it implies that you click out of the search box to register the new entry, which is again not that great.

**Comment by vvo** [comment]
I think the current behavior is fine in term of UX (only pushing a new entry after 700ms). But we may have an issue because of updating the url bar at each keystroke. This is platform dependent as @bobylito said so we need to be careful here before taking a decision.

I am not sure in term of UX updating the url bar at each keystroke is the best idea, the more I use it the more it "feels" less performant because not only the whole screen is updating but also the url bar which can be confusing (== where do I need to look on my screen? urlbar? webpage?). It can be taken as "noise"

Maybe just updating the urlbar when we push a new state could be sufficient.

As for the performance problem of @olance it may be related to the replaceState at each keystroke, we need a real video comparison without any dev tool nor extension loaded of the before/after activating it @olance, thanks!

**Comment by bobylito** [comment]
@vvo Well internally each keystroke is a new state, and a new search. Do you have ideas on how it could work with the pattern you propose?

**Comment by vvo** [comment]
Sorry I meant "maybe updating the url bar only when using history.pushState" which means only after the thresold.

Today we both update  it at each key stroke AND after the thresold

**Comment by seafoox** [comment]
What about updating it only when the user focusses out of the input?
That's a predictable event, and will avoid pushing new states when its not needed.

**Comment by vvo** [comment]
I would prefer updating the url only after the thresold and not on every keystroke. @bobylito you implemented the on keystroke updating on the url, what do you think of removing it to only update it after the thresold?

**Comment by vvo** [comment]
Moved to #837
