### ISSUE TITLE
Allow updating the configuration of widgets and allow forcing a render

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#852]
Goal: be be able to update the hits (or other) widget templates or limit and then force a re-render.

```js
hits.updateConfiguration({});
hits.forceRender();
```

Use cases:
- #753 
- #845 

This will not be so easy in term of implementation:
- are every widget worth having those methods?
- how to do it easily without a lot of boilerplate code?

**Comment by gregquat** [comment]
For the case of #845, I can "update" the configuration of the **hits** widget by overriding it (add a new widget in the same container), but with another template.

Then, I call `search.start()`.
It works with little side effects (for the moment, I only have a problem with one other widget. See #845 for more information).

I don't know if it helps or not because I don't know your lib at all, but I have the feeling it's not far from already working.

**Comment by vvo** [comment]
We will provide removeWidget #1065 as long with sometime allowing updating configuration like for the rangeSlider #1069
