### ISSUE TITLE
Incompatibility with IE9 and urlSync

### ISSUE THREAD

**Issue by amelielescure** [algolia/instantsearch.js#890]
Hi,
I initialized instantsearch.js by passing a parameter to UrlSync:
```javascript
      urlSync: {
        trackedParameters: [
          'query',
          'page',
          'attribute:*'
        ]
      }
```
Unfortunately I have a incompatibility problem with IE9 despite having well add polyfill script ...
```html
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<!--[if lte IE 9]><script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script><![endif]-->
```
Here is the error every time I try to click on a filter "refinementList" or "hierarchicalMenu":
![bhjbh n](https://cloud.githubusercontent.com/assets/2580321/13463508/e00797d6-e08c-11e5-8640-cc6366228ca1.png)

When I put URLSync false I do not have this error, so obviously it's from the construction of URL?

**Comment by vvo** [comment]
Hello, yes good point. IE9 has no history object: http://caniuse.com/#feat=history and there is no good polyfill because the feature of having clean URLS (without #) in IE9 just doesn't exists.

To fix this, you can use the # in IE9.

You can instantiate urlSync with useHash: true for IE9. We do not do it automatically.

```js
  urlSync: {
    trackedParameters: [
      'query',
      'page',
      'attribute:*'
    ],
    useHash: window.history && 'pushState' in window.history ? false : true,
  }
```

Let me know how it goes.

**Comment by amelielescure** [comment]
Perfect, it Works :) Thanks
