### ISSUE TITLE
Toggled element still displays in current refined values when false

### ISSUE THREAD

**Issue by davidpike7** [algolia/instantsearch.js#905]
We're currently using a toggle widget to display hits flagged as a 'special'. On initial render it shows up in the current refined values even when false. Once it is removed it then works correctly.

e.g.

<img width="315" alt="screen shot 2016-03-07 at 22 24 57" src="https://cloud.githubusercontent.com/assets/1872727/13568153/7b3208ac-e4b3-11e5-9d7c-c518d8a5b408.png">

**Comment by vvo** [comment]
Can you check and give me:
- the version you are using (we recently published a new version)
- the url when the filter is showing in current filters while not activated in the display
- the way you initialize the toggle widget (options)
- an example value for the "specials" attribute you are using (is it a boolean?)

Thanks

**Comment by davidpike7** [comment]
- 1.3
- The URL doesn't show any query params on initial load when the current filters is showing 'specials' on page load but if I add and remove it I get the following:
 
`search?q=&hPP=15&idx=journeys&p=0&fR[hasSpecialOffer][0]=false&is_v=1`

The plugin was initialized like so:

```javascript
    this.instantsearch.addWidget(
        instantsearch.widgets.toggle({
            container: '#journeys-specials-widget',
            attributeName: 'hasSpecialOffer',
            label: 'Only show specials',
            templates: {
                item: refinementItem
            },
            values: {
                on: true,
                off: false
            },
        })
    );
```

Example of field from algolia dashboard `hasSpecialOffer: false`

**Comment by vvo** [comment]
Do you have any other widget that is activated on the `hasSpecialOffer` attribute?

**Comment by davidpike7** [comment]
The only other mention of `hasSpecialOffer` is in the current refinements widget

```
this.instantsearch.addWidget(
    instantsearch.widgets.currentRefinedValues({
        container: '#journeys-current-refined-widget',
        clearAll: 'after',
        attributes: [
            {
                name: 'price',
                label: '',
                transformData: function(item) {
                    item.name = accounting.formatMoney(item.name);
                    return item;
                },
                template: '{{#operator}}{{{displayOperator}}} {{/operator}} {{name}}'
            },
            {
                name: 'hasSpecialOffer',
                label: 'Specials',
                template: '{{label}}',
            },
            {
                name: 'numberOfDays',
                label: 'days',
                template: '{{#operator}}{{{displayOperator}}} {{/operator}} {{name}} {{label}}'
            },
        ],
        templates: {
            header: 'Current Filters'
        },
    })
);
```

I can provide the staging URL if that is any help?

**Comment by vvo** [comment]
> I can provide the staging URL if that is any help?

Oh yes it would help a lot! If it's a private one, send it to support@algolia.com

**Comment by vvo** [comment]
For anyone wondering,

The default `values` option is: `values: {on: true, off: undefined}`. Which means: when "on", refine the attribute with `true` (boolean). When off, refine with `undefined` => show both true and false values.

So if you do not provide the `values` option, when the widget initializes, we will not refine on anything.

Let's say you have a "free shipping" toggle, it will show you by default both free and not free shipping. When you activate it, it will only show free shipping articles.

Given your context, this might not be what you want, you might for instance for to refine with `false` on initialization and when off.

To do so, pass `values: {on: true, off: false}`. But as soon as you do so, you will always have the default toggle "false" showing in the current refined values widgets. Because we did refine on the attribute with `false`.

This is why @davidpike7, in your example, it shows the filter inside the current refined values by default: this is the off value.

1. How could we make this more clear?
1. Is this in the end what you want? Maybe you want the default behavior (true/undefined)
1. Maybe you would want a "doNotRefineOnInit" option? But for users this would be not accurate.

Thanks again for being an awesome user of instantsearch.js and to give us feedback!

**Comment by davidpike7** [comment]
Thanks for the explanation @vvo. I've removed `off: false` from config and its working well now

**Comment by vvo** [comment]
Closing
