### ISSUE TITLE
numericRefinementList should be able to filter on multiple ranges

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch.js#924]
For example, I would like to be able to provide this:

- [ ] < 500
- [ ] 1499-5000
- [ ] 5000+ 

And be able to select multiple ranges:

- [x] < 500
- [ ] 1499-5000
- [x] 5000+ 

Right now, we only provide radio buttons by default because the default refinement option is to select only one range.

Being able to select multiple ranges could be nice, sometimes useful.

**Comment by vvo** [comment]
This is already feasible by just providing a different template (checkboxes). Thx @maxiloc

**Comment by redox** [comment]
> This is already feasible by just providing a different template (checkboxes). Thx @maxiloc

Nope, updating the template won't let you select multiple values. The widget has been designed to fit Amazon's UX; and therefore [only display the refined range if any](https://github.com/algolia/instantsearch.js/blob/master/src/widgets/price-ranges/price-ranges.js#L163-L167) -> so you won't have the ability to click other ranges since they won't even be displayed.

**Comment by redox** [comment]
> Nope, updating the template won't let you select multiple values. The widget has been designed to fit Amazon's UX; and therefore only display the refined range if any -> so you won't have the ability to click other ranges since they won't even be displayed.

Arg, I was speaking about the `PriceRanges` widget /o\
