### ISSUE TITLE
urlSync.threshold seems not to work

### ISSUE THREAD

**Issue by powtac** [algolia/instantsearch.js#943]
According to the [docs](https://community.algolia.com/instantsearch.js/documentation/#initialization)

![unbenannt](https://cloud.githubusercontent.com/assets/36167/13926061/f35e5826-ef8a-11e5-80ca-60f97fb2f599.PNG)

`urlSync.threshold` should update the URL but delayed by700 ms. This seems not to work for me, it even seems to block typing into the search box while the URL is beeing updated. (Can not be proven.)

So it works, the URL is updated, but it definitely does not delay the URL update by 1000 ms. 

```
var search = instantsearch({
	appId:		'...',
	apiKey:		'...',
	indexName:	'...',
	urlSync:	{
		useHash:	true,
		threshold:	1000 // This seems not to work
	},
	searchFunction: function (helper) {
		helper.search();
	},
	searchParameters: {
		typoTolerance: true,
	},
});

search.addWidget(
	instantsearch.widgets.searchBox({
		container: 		'#q',
		autofocus:		true,
		wrapInput:		false,
		queryHook:		$.throttle(function(query, search) {
			if ($.trim(query).length == 0) {
				return false;
			} else { /* set empty result list */ }
			search(query);
	    }, 1000),
	})
);
```
Or is this only about the browser history?

**Comment by bobylito** [comment]
Hi Simon, thanks for the issue. Our doc is lacking real explanation about that. The URL sync mechanism is implemented in a way that it will update the URL (and not creating new browser history steps) if under the threshold. Beyond the threshold it will create a new entry. It is not using throttle or debounce.

**Comment by powtac** [comment]
@bobylito Ah! I see, so either the "internal" browser history is used with `useHash: true` OR a "real" browser history is rendered into the browsers search bar. 

Anyway the threshold seems not to be recognized.

**Comment by vvo** [comment]
@powtac at each keystroke we update the url (no matter if we use native browser history or fake one using location.hash).

Then, when using native browser history API, on top of updating the url at each keystroke, we create a new history state after the thresold.

The states we are talking about are the ones used when you hit "back", only. They should represent the times where you stop typing/meaningful queries/half queries.

Here's an example:
- history state is empty query
- t0: type t (url bar has: t, history state is empty query)
- t0+30ms: type e (url bar has: te, history state is empty query)
- t0+600ms: type s (url bar has: tes, history state is empty query)
- t0 + 700ms: type t (url bar has: test, new state is created)
- t0 + 900ms: type e (url bar has: teste, history state is "test")

Then if you stop writing, url bar is "teste", history state should be "teste" (because you stopped typing for more than 500ms more (900 + 500 = 1400 so two times thresold).

Then if you hit "back button", you will go to "test" and if you hit back button again you will go to empty query.

Hope this long explanation is clearer.

I think a lot of people thinks thresold might be a debounce url bar set. It's just the time after we create a new history state entry in the browser.

**Comment by powtac** [comment]
@vvo clear! I got it. 

Anyway. The case I tried to describe in [this ticket](https://github.com/algolia/instantsearch.js/issues/943#issue-142403425) is, that it looks like the **hash URL** is updated immediately and not only every 700ms. I thought it only will be updated once every 700 ms as you described it. But I can not see a delay even when setting `threshold` to 10000 ms. Or is the `threshold` option only for `useHash: false`?

**Comment by vvo** [comment]
In both cases no matter the value of thresold the URL is always updated. Thresold is only saying "every 700ms create a new state that will be available when using the back button".

So, if you use "useHash", do you have a state per letter when clicking on back button? That would be a bug.

Thanks

**Comment by powtac** [comment]
> So, if you use "useHash", do you have a state per letter when clicking on back button? That would be a bug. 

I will check that! Thanks for clarifying!

**Comment by powtac** [comment]
Definitely the value of threshold is not recognized. When I set it to 10000 the URL is updated roughly every second. Probably every 700 ms but not every 10 seconds!

**Comment by vvo** [comment]
Ok thanks for that I will have a look

**Comment by vvo** [comment]
I have been double checking this and it's "on purpose" that we update the url at every keystroke to provide the right feedback to our users.

Then, the thresold is only the minimum time between two search states where we decide to create a new state.

So when putting thresold: 10000 (10s) it means that we will create new search states every 10s. The thresold is our way of saying "After xxxms of inactivity, we consider the state to be one to remember when going back".

Example with 10s:

- t0 page load (enpty query)
- t0+1 type hello (url is updated like h, e, l, l, o
- t0+8 type mom (url is updated like m, o, m)
- t0 + 9 click on back button (url is back like at t0 and query is empty)

You are now back at the initial state because we were not able to create any search state.

I understand this may not be the behavior you might want to build into your application but this is the correct behavior given the implementation.

I will update the documentation on this part.

If you want to have a different behavior or a new parameter then please open a new issue. Thanks!
