### ISSUE TITLE
Pagination url bug with base attribute

### ISSUE THREAD

**Issue by jpchaput** [algolia/instantsearch.js#970]
Bug #790 has been fixed.

But the link in the pagination are still wrong because they are relative (starting with ? or #).

The same problem is present in the url generated by currentRefinedValues widget.

Thanks for your help

**Comment by vvo** [comment]
I am unsure there's an easy way to sort this out without creating a new API entry somewhere.

Basically here are the possible cases:
- html is served from http://www.example.com. OK
- html is served from http://www.example.com/subfolder/. OK
- html is served from http://www.example.com/subfolder/. Base href is /subfolder/. OK
- html is served from http://www.example.com. Base href is /subfolder/ NOOK
- html is served from http://www.example.com/subfolder/. Base href is /anotherfolder/ NOOK

OK => everything works, links are the right ones
NOOK => interface works, links are not the right ones. Since we have relative links by default, they will use the base href by default.

One solution to this, would be to provide an API entry like absoluteLinks: true in instantsearch.js.

OR maybe we just need to preprend the current webpage url to the links, this would solve every cases I believe. What do you think @jpchaput?

**Comment by jpchaput** [comment]
Best way should be an option in urlSync : absoluteLinks: true or baseHref:'http://www.example.com/search/'

**Comment by vvo** [comment]
What about constructing links that are always relative to the current window.location instead, that would fix the bug for good. Are there cases where your search page is at /search/ and you want the links to point at /search-other-page/?
